### ISSUE TITLE
It would be cool if parameters could be factories themselves

### ISSUE THREAD

**Issue by justinmchase** [typestack/typedi#104]
Perhaps there is a way to do this but I couldn't figure it out, something like this:

```ts
@Service()
export class Example {
  constructor(private worker: () => Worker) {
  }

  public check() {
    return this.worker().id;
  }
}
```

I am having issues with circular dependencies and its really tempting to do `private worker: Worker` but of course that doesn't work. I have to do an extra layer of indirection and am not sure the best way to do it.

**Comment by NoNameProvided** [comment]
You can use default parameters: 

```ts
@Service()
export class Example {
  constructor(private worker =  Container.get(Worker)) { }

  public check() {
    return this.worker().id;
  }
}
```
