### ISSUE TITLE
possibly inappropriate name

### ISSUE THREAD

**Issue by ducin** [typestack/typedi#105]
According to the names used in the docs, the library claims it's implementing the _Dependency Injection_ pattern. However, going through code examples, most of them _pull_ certain dependencies from an object that knows where they all are. The dependencies are actually not injected, but pulled. Moreover, from the constructor signature you cannot tell what the dependencies are. This pattern is called a [_service locator_](https://en.wikipedia.org/wiki/Service_locator_pattern) and it's targeting the same concern - decoupling, but is a completely different pattern.

In current shape the docs are confusing, since claiming implementing a different pattern that it actually implements.

**Comment by kucharskimaciej** [comment]
> from the constructor signature you cannot tell what the dependencies are

What do you mean by that? Seems pretty clear in most cases I've seen.

**Comment by ducin** [comment]
With dependency injection, your dependencies are _injected_ into the
constructor (or setters), so you can see the list of all dependencies of a
unit just by looking at the constructor. Here, you can't, although it's not
the most important issue.

What you have is NOT dependency injection, but a service locator. It's a
different pattern, actually, considered by many as an antipattern
(example/pl: https://devstyle.pl/2016/02/11/antywzrorzec-service-locator/ )

pt., 4.10.2019, 15:47 użytkownik Maciej Kucharski <notifications@github.com>
napisał:

**Comment by kucharskimaciej** [comment]
How is that the case [here](https://github.com/typestack/typedi/blob/master/sample/sample3-service/CoffeeMaker.ts)?

**Comment by ducin** [comment]
It is the case [here](https://github.com/typestack/typedi/blame/b2e0a2fc60fabd4bde68e943a06a550305041c69/README.md#L32) and [here](https://github.com/typestack/typedi/blame/b2e0a2fc60fabd4bde68e943a06a550305041c69/README.md#L59-L63) and a couple of other `.get` calls.

With DI, dependencies are passively injected into the class. However, if you ask for the dependencies with `.get(X)`, it's not injection anymore, because you pull them.

Your library implements and allows both approaches. The first few examples in the docs demonstrate service locator, not DI. However, they are then followed by DI. Both SL and DI are form of Inversion of Control.

[Here](https://designpatternsphp.readthedocs.io/pl/latest/More/ServiceLocator/README.html) you've got another demonstration of service locator which is how your code works.

**Comment by kucharskimaciej** [comment]
I'm perfectly clear what the patterns are, no need to link to 3rd article on that, thanks.

My point is that this sentence: 
> In current shape the docs are confusing, since claiming implementing a different pattern that it actually implements.

is factually not true, as per
> they are then followed by DI

The package indeed implements the Dependency Injection pattern, as stated in the package name. It also happens to implement a complimentary SL pattern.

It should be more clear in the readme which pattern is demonstrated in the given example, but it's surely not enough to warrant changing the name of the package.

**Comment by ducin** [comment]
People trust what they read in docs. If someone is unaware of the
distinction between SL and DI, they might get a completely wrong picture of
what DI is, basing on the current shape of docs and what your lib offers.
The library name suggests it's DI only (*typedi* - and not, for instance,
*typed-injector*) and first few examples picture SL without any explanation
on what pattern is applied. I'm not discussing the targets your lib
achieves - instead, I'm pointing out that the docs should not illustrate SL
and call it DI everywhere.

That said, take it or ignore it :)

>
