### ISSUE TITLE
Spring like bean creation

### ISSUE THREAD

**Issue by benkeil** [typestack/typedi#106]
Is it possible to create instances of a class like in Spring? Something like:

```typescript
@Service()
export class DynamodbConfig {

  @Bean(DocumentClientToken)
  public createDocumentClient(@Inject(AwsRegionTableToken) region: string): DocumentClient {
    return new DocumentClient({ region: region });
  }
}
```

**Comment by NoNameProvided** [comment]
Currently, we don't support this. Java and JS ha a vastly different programming style. What makes sense in Java not so much in JS. I don't see what actual advantage would this bring to the end-user. Closing this as wontfix, if you believe this is a must-have feature, please write detailed reasoning about what advantages this approach has over the current solutions.
