### ISSUE TITLE
Can't inject type-safe interface using token more than 1 level of dependencies.

### ISSUE THREAD

**Issue by HuskyMoonMoon** [typestack/typedi#110]
I have services that has 2 level injections as follow.
```ts
interface IFoo {
 foo: string;
}
const foo = new Token<IFoo>();

interface IBar {
  bar: string;
}
const bar = new Token<IBar>();

@Service()
class FooService implements IFoo {
  foo: string
}

@Service()
class BarService implements IBar {
  @Inject(foo)
  fooService: IFoo;
}

@Service()
class FooBarService {
  @Inject(bar)
  barService: IBar;
}

Container.set(foo, new FooService());
Container.set(bar, new BarService());
Container.get(FooBarService);
```
I'm trying to get `FooBarService`, depends on `IBar` that has implementation depends on `IFoo`. I get `FooBarService` instance with `barService` injected with instance, but `barService.fooService` is undefined.

I can do class injection in multiple level, including circular injection using `Inject((type) => Classname)` easily. But no hope for token. Anyone has a suggestion to encounter this problem?

**Comment by zebieksts** [comment]
I believe that I faced the same or very similar issue. My code was like below. Message bloker is undefined when OperationsPublisher is initialised. Similar injections into abstract parent class where instances are injected instead of token work fine. I ended up adding constructors to each child in this case, which is a bit ugly but works.
`
@Service()
export abstract class AbstractPublisher {
  constructor(
    @Inject(MessageBrokerService) protected messageBroker: MessageBroker
  ) { 
  console.log('Message broker', messageBroker);
 }
...
}

@Service()
export class OperationsPublisher extends AbstractPublisher { 
...
}

export const MessageBrokerService = new Token<MessageBroker>();
`

**Comment by NoNameProvided** [comment]
You ~don't~ incorrectly register the token with the service. When you write set the class instances to for the token explicity you overwrite the class registration done in the `@Service` decorators.

Also never use interfaces as they are compiled away. The few rule of thumb with TypeDI: 

- always use classes with TypeDI
- always use the `@Service` decorator
- never call `new MyService()` on your own if you want the dependencies to be handled using `Container.get` instead

The correct usage:

```ts
import { Token, Service, Container, Inject } from 'typedi';

interface IFoo {
 foo: string;
}
const FOO_TOKEN = new Token<FooService>();

interface IBar {
  bar: string;
}
const BAR_TOKEN = new Token<BarService>();

@Service()
class FooService implements IFoo {
  foo: string
}

@Service(BAR_TOKEN)
class BarService implements IBar {
  @Inject(FOO_TOKEN)
  fooService: IFoo;

  bar: string;
}

@Service(FOO_TOKEN)
class FooBarService {
  @Inject(BAR_TOKEN)
  barService: IBar;
}

const instance = Container.get(FooBarService);
// instance.barService exists
``` 

But actually you don't even need the tokens. You can just use `@Inject` with the requested type: 

```ts
import { Token, Service, Container, Inject } from 'typedi';

interface IFoo {
 foo: string;
}

interface IBar {
  bar: string;
}

@Service()
class FooService implements IFoo {
  foo: string
}

@Service()
class BarService implements IBar {
  @Inject(type => FooService)
  fooService: IFoo;

  bar: string;
}

@Service()
class FooBarService {
  @Inject(type => BarService)
  barService: IBar;
}

const instance = Container.get(FooBarService);
// instance.barService exists

console.log(instance.barService)
```

PS: Hidden the unrelated comment from @zebieksts
