### ISSUE TITLE
ScopedContainer Services don't save transient property

### ISSUE THREAD

**Issue by Nerixyz** [typestack/typedi#122]
https://github.com/typestack/typedi/blob/ba2d73f245ec92f8d67538e2409ec55d2c5cdb7d/src/ContainerInstance.ts#L115
Here, a service that's not yet in the scoped conatainers services is put into the services. 
That's at least the idea. But only the value is put into the set method. This results into the service properties being discarded. To fix this, this line sould **probably** be:
```ts
this.set({
     ...clonedService,
     type: identifier, id: identifier
});
```
*Maybe I didn't read the code enough but that's wat worked. Also: if global is set to true, this works.**

**Comment by NoNameProvided** [comment]
Hi! 

Can you elaborate? I don't exactly understand what do you mean.

**Comment by NoNameProvided** [comment]
Closing as no answer from the OP. If you are still experiencing any problem please open a new issue where you include a minimal reproduction case (only TypeDI package and some example classes should be used to showcase the problem)
