### ISSUE TITLE
question: <Implementing repository injection using typedi-typeorm.>

### ISSUE THREAD

**Issue by saurav-commits** [typestack/typedi#1239]
**I was trying to...**
 
<!-- I want to inject this repository (FieldSettings) into controller (FieldSettingsController).
<!-- Here is my repository code.
`
import { Service, Container } from 'typedi';
import { Entity, PrimaryGeneratedColumn, Column, Repository, getRepository } from 'typeorm';
import { Logger } from '@services/logger.service';
@Service()
@Entity()
 class FieldSettings {

  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  name: string;

  @Column({default : false  })
  is_selected: boolean;

  constructor(payload: Record<string, unknown>) {
    Object.assign(this, payload);
  }
}
Container.set('FieldSettingsRepository', fieldSettingsRepository);
  Container.set('FieldSettings', getRepository(FieldSettings));
  Logger.log('info', `Nitin is ${FieldSettings}`)

export { FieldSettings };`

<!-- Here is my controller code.
 
`
import {Request} from 'express';
 import { getRepository } from 'typeorm';
 import { IResponse } from '@interfaces';
 import { success } from '@utils/common.util';
 import { FieldSettings } from '@models/field-settings.model';
 class FieldSettingsController {

     private static instance: FieldSettingsController;

     private constructor() {
     }

     static get(): FieldSettingsController {
         if (!FieldSettingsController.instance) {
             FieldSettingsController.instance = new FieldSettingsController();
         }
         return FieldSettingsController.instance;
     }
   
     async createFields(req: Request, res: IResponse): Promise<void> {
         try {
             const fields = new FieldSettings({
                 name : req.body.name
             })

             await getRepository(FieldSettings).save(fields);

             res.status(200).json(success('', {}, res.statusCode));
         } catch (err) {
             console.log('err', err);
             res.status(400).json(success('', {}, res.statusCode));
         }
     }

const fieldSettingsController = FieldSettingsController.get();

export {fieldSettingsController as FieldSettingsController}
`
<!-- Thanks in advance.

**Comment by attilaorosz** [comment]
Could you provide more info?

**Comment by saurav-commits** [comment]
I am Sorry @attilaorosz  I have moved to redis.
