### ISSUE TITLE
Verbose logging

### ISSUE THREAD

**Issue by avin-kavish** [typestack/typedi#125]
Just wondering if it's possible to log dependency resolution requests verbosely. Sort of a debug log, to see when and which classes get instantiated.

**Comment by NoNameProvided** [comment]
No. You can either debug your code via `node --inspect-brk ./your-script.js` (see [Debugging guide](https://nodejs.org/en/docs/guides/debugging-getting-started/) for details). If you would like to log DIs in production environment you can wrap your classes with a custom decorator which logs when the class is initialized.
