### ISSUE TITLE
Passing params to Container.get() or Container.of()

### ISSUE THREAD

**Issue by flux627** [typestack/typedi#127]
In the inline documentation, the `Container.get()` method says the following:

> Retrieves the service with given name or type from the service container. **Optionally, parameters can be passed in case if instance is initialized in the container for the first time.**

Emphasis mine. It didn't seem like this was accurate, as there was no overload that seemed to support this. I did a little research, and discovered that this feature did indeed exist at one point, but was removed seemingly without any communicated justification in this commit: https://github.com/typestack/typedi/pull/18/commits/79f3435f42502ee2410052c7e0391eb94fd689f0.

So I am here to ask- what was the justification? Is there a replacement for the use-cases this supported?

The main use-case I am looking for is for passing parameters to factories of transient instances, so I can configure them on a per-request basis.

**Comment by flux627** [comment]
I've been thinking about this a bit differently. It seems that, for consistency, these parameters should be a part of the container configuration itself, and the dynamic use-case corresponds with the use-case for scoped containers. Proposed API:
```
Container.of('my-new-scoped-container', context)
```
`context` is then passed as a parameter to factories:
```
Container.set({
  id: 'my-service',
  factory: (context: any) => {
    return { myCustomParam: context.param }
  }
})
```
or injected as constructor parameters:
```
@Service()
class MyService {
  public myCustomParam: string
  constructor(@ContainerContext() context: any) {
    this.myCustomParam = context.param
  }
}
```

**Comment by weoreference** [comment]
Hello, I am wondering if you have any further ideas on this?

How to pass dynamically generated params for Container.get() ?

I was hoping for something like this...

`
let smithGreeter = Container.get(Greeter, 'John Smith'')

smithGreeter.greet() // 'Hello, Mr. John Smith'
`

Is this what you would call a factory resolver?

**Comment by jaschaio** [comment]
Having the exact same question as @weoreference

**Comment by jaschaio** [comment]
Same request in #119 btw.

Any insights @pleerock

**Comment by jaschaio** [comment]
I cloned the repository locally, running test fails.

This doesn't work for me https://github.com/typestack/typedi/blob/master/test/Container.spec.ts#L195:

```
        it("should have ability to pre-specify class initialization parameters", function() {

            @Service()
            class ExtraService {
                constructor(public luckyNumber: number, public message: string) {
                }
            }

            Container.registerHandler({
                object: ExtraService,
                index: 0,
                value: containerInstance => 777
            });

            Container.registerHandler({
                object: ExtraService,
                index: 1,
                value: containerInstance => "hello parameter"
            });

            Container.get(ExtraService).luckyNumber.should.be.equal(777);
            Container.get(ExtraService).message.should.be.equal("hello parameter");

        });
```

The Constructor still only receives a single parameter (container).

Anyway, a workaround that does work is using `Container.set()` before calling `Container.get()`:

```js
class Test {

    constructor( ...args ) {

        console.log( "args", args );

    }

}

Container.set( {
    id: Test,
    factory: () => new Test( 'something' ),
} );

// Outputs "args [ 'something' ]"
const test = Container.get( Test );
```

Just be aware that the Class constructor won't receive `container` anymore as the last argument.

**Comment by jaschaio** [comment]
@pleerock any chance to get any insights from you on the topic? My workaround is not really a suitable alternative to just passing parameters to `Container.get()`.

**Comment by weoreference** [comment]
So -- no solution to this?

**Comment by NoNameProvided** [comment]
> So I am here to ask- what was the justification? Is there a replacement for the use-cases this supported?

Yes your use-case is currently supported, see the example below.

> The main use-case I am looking for is for passing parameters to factories of transient instances, so I can configure them on a per-request basis.

I don't agree with the rationale behind this feature request. This can be easily achieved without extra features via using a `Token` to inject the dynamic data. Below is a working minimal example: 

```ts
import 'reflect-metadata'
import { Container, Inject, Service, Token } from "typedi";

export const ContextToken = new Token('REQUEST_CONTEXT');

@Service({ transient: true })
export class YourService {
  public constructor(
    @Inject(ContextToken) 
    protected context: any,
  ) { }
}

// Request A
const requestContainerA = Container.of('requestA');
requestContainerA.set(ContextToken, { param: 'requestParamA'});

// Request B
const requestContainerB = Container.of('requestB');
requestContainerB.set(ContextToken, { param: 'requestParamB'});

const serviceInstanceA = requestContainerA.get(YourService);
const serviceInstanceB = requestContainerB.get(YourService);

console.log({ serviceInstanceA, serviceInstanceB });
// both service will have the custom value inserted into it
```

Adding a feature for this just would make an N+1 way to inject stuff into the service. 

So my take on this issue is that we already support the requested scenario and there is no clear benefit of having this feature expect to have minor syntactical sugar, which makes 2 lines of code into one while locking up either the start or the end of the constructor parameters opening a heap of possible issues with it. 

I am closing this as solved. If you still experience issues regarding this topic, continue the discussion and I will reopen the ticket.

**Comment by flux627** [comment]
I see, this makes sense. Thanks!

**Comment by flux627** [comment]
I think there are other concerns besides mine in this thread- I encourage @weoreference or @jaschaio to continue the conversation if this doesn't meet their use-cases.

**Comment by NoNameProvided** [comment]
Definitely, if anyone still experiences any issue please feel free to ask, however please open a new issue for it with a minimal code example. Thanks! 

PS: I flagged this issue as needs docs, we should add my example above as I believe this is a quiet common use-case.
