### ISSUE TITLE
feature: add support for ES modules

### ISSUE THREAD

**Issue by desmap** [typestack/typedi#129]
TypeDI is incompatible with Node 13 and 14 when using ES6 Modules (e.g. in Node 14 you activate it with `"type": "module"` in your `package.json`). 

I receive the following error: 

```
api    | import { Service } from 'typedi';
api    |          ^^^^^^^
api    | SyntaxError: The requested module 'typedi' does not provide an export named 'Service'
api    |     at ModuleJob._instantiate (internal/modules/esm/module_job.js:92:21)
api    |     at async ModuleJob.run (internal/modules/esm/module_job.js:107:20)
api    |     at async Loader.import (internal/modules/esm/loader.js:179:24)
```

**Comment by MichalLytek** [comment]
Why CCing me? I'm not a contributor of this project:
https://github.com/typestack/typedi/graphs/contributors

**Comment by desmap** [comment]
@MichalLytek apologies for just CCing you without further infos; since DI is an integral part of larger TypeGraphQL apps and typedi fits syntax-wise well to your lib, this incompatibility also might impact  your lib or in general TypeGraphQL projects.

@pleerock to give more background info: when using tsc with the the ts option module = commonjs it's no problem because typedi works with commonjs but I had to switch to es6 modules because I integrated next js into the stack for fe which enforces es6 modules (it overwrites that specific option every time to esnext). So, since next is quite popular and typedi should be future proof, how can we can fix it? Just checked typedi's sources and the Service exports look good, so IDK, maybe you know what's going on

**Comment by desmap** [comment]
@MichalLytek I am just ripping out typedi out of my app which goes fast because I haven't went all-in with DI but it's still a bit unfortunate. So maybe a small note in your docs would helpful for other driving by.

**Comment by MichalLytek** [comment]
@desmap 
TypeGraphQL is not a part of the typestack.
The only TypeGraphQL requirement for DI lib is the `.get()` method of container, so it works with every other DI lib in Node.js.
TypeDI is mentioned in docs/examples only because of it's simplicity, like Apollo Server is even as it's super slow TBH (https://github.com/benawad/node-graphql-benchmarks#benchmarks) 😉
For production apps I would use https://github.com/microsoft/tsyringe.

**Comment by desmap** [comment]
ok good to know but tsyringe lacks Inject and syntax is kind of odd. 

whatever what's your favorite graphql server besides apollo then (good list from from ben btw)?

**Comment by hc-codersatlas** [comment]
@MichalLytek does tsyringe even have a `.get()`? Tried to add the container and it gives an error. Looking at the source code tsyringe has a method called `.resolve()` isntead.

**Comment by MichalLytek** [comment]
@hc-codersatlas 
```ts
await buildSchema({
  container: {
    get: (cls: any) => tsyringeContainer.resolve(cls),
  },
});
```

**Comment by NoNameProvided** [comment]
This happens because TypeDI ships the code with JS we need to compile the project with import/export enabled and add a secondary entry-point for it.

**Comment by NoNameProvided** [comment]
This has been added in 45b0974a2a4d563811b43887a49433aed35f2aee. It will be released in the next version.
