### ISSUE TITLE
question: are interceptors supported?

### ISSUE THREAD

**Issue by mouimet-infinisoft** [typestack/typedi#132]
Hello everyone

Is there a feature in typedi for Interceptors like there is in Microsoft Unity?

If not, is there a technical reason?

Would it be interesting to implement an @Intercept() decorator?

Regards

**Comment by NoNameProvided** [comment]
Currently, we don't support interceptors. 

> like there is in Microsoft Unity?

We don't know how interceptors work in Unity,

> Would it be interesting to implement an @Intercept() decorator?

I don't see any practical benefits. What functionality would you like to achieve which requires interceptors? And how would they behave exactly?
