### ISSUE TITLE
MissingProvidedServiceTypeError  when trying to use Container in app.ts

### ISSUE THREAD

**Issue by jefjos** [typestack/typedi#133]
I'm working on a Node.js Fastify based app service, and using TypeDI for dependency injection.

Some services I use need async initialization.

MyService.ts
```ts
export class MyService {
  constructor() {  }
    
  public async init() {
     // some cod here
  }
}
```

I am trying to initialize the service at application startup so that any service doing `Container.get(MyService)` gets this initialized instance of `MyService`.

app.ts
```ts
export default async function(fastify: FastifyInstance, opts: Options, next: Function) {
  // This loads everything under routes 
  fastify.register(autoload, {
    dir: path.join(__dirname, "routes"),
    options: opts,
    includeTypeScript: true,
  });
    
  await Container.get(MyService);
    
  next();
}
```

server.ts
```ts
import app from "./app";
    
  const server = fastify({
    logger: logger
  });
    
  server.register(oas, docs);  
  server.register(app);
    
  server.ready(err => {
    if (err) throw err;
      server.oas();
    });
    
    server.listen(config.port, (err) => {
      if (err) {
        server.log.error(err);
        process.exit(1);
      }
      server.log.info(`server listening on ${server.server.address()}`);
    });

export default server;

```

My attempt to initialize MyService is failing:

> MissingProvidedServiceTypeError [ServiceNotFoundError]: Cannot determine a class of the requesting service "undefined"

Any hints to what I'm doing wrong?  I'm new to nodejs and would really appreciate some insight.

**Comment by Guttz** [comment]
I have the same problem.. Found your post in SO too.

I didn't quite understand what you did to solve this. Could you post the code sample here?

**Comment by NoNameProvided** [comment]
You need to decorate your classes with `@Service` decorator. Minimal working example: 

```ts
import { Service, Container } from 'typedi';

@Service()
export class MyService {
  constructor() {  }
    
  public async init() {
     // some cod here
  }
}

const instance = Container.get(MyService);
```

PS: This is the number one issue. Please read the documentation with more care and check existing and closed issues before creating a new one.
