### ISSUE TITLE
question: where did the docs go?

### ISSUE THREAD

**Issue by lnmunhoz** [typestack/typedi#141]
I can't really remember, but a few weeks ago when I started using the library there was a few docs available in the website. Recently I looked again for the Container API docs and I could not find here in the `docs` folder and the website is completely empty.

What happened with the old docs? Did the docs existed before or is my mistake?

**Comment by lnmunhoz** [comment]
Apparently is [here](https://docs.typestack.community/typedi/v/develop/01-getting-started) under `Old Documentation`. I only spotted after creating the issue.

**Comment by NoNameProvided** [comment]
You can find only the not yet reworked parts of the documentation under the Old documentation page, the rest of it had been reworked and structured. 

You can also find the documentation under the docs/ folder in the repo as markdown.
