### ISSUE TITLE
question: Documentation/suggested patterns for interface implementation may be confusing to people

### ISSUE THREAD

**Issue by South-Paw** [typestack/typedi#143]
Hi there, this is a bit more of an explanation of my journey with the hope that maintainer and/or other users will find this useful.

After spending a few hours on trying to work out what I was doing wrong, I finally cracked it and I believe its due to a few misconceptions I maybe have picked up from the documentation.

Related: #79

# I was trying to...

I was trying to implement a rough DDD pattern in my application using typedi. I thought that because typedi provides the `Token` class, I could something along the lines of the following (please note that these are all different files, which may contribute to the problem? I suspect it might work if you place these all in a single file... also note that I've tried to break it down to the smallest reproduction possible)

<details>
<summary>Code example 1</summary>

```ts
// tokens.ts
import { Token } from 'typedi';

export const ServiceAToken = new Token<string>('ServiceA');
export const ServiceBToken = new Token<string>('ServiceB');
```

```ts
// ServiceA.ts
import { Service } from 'typedi';
import { ServiceAToken } from './tokens';

export interface IServiceA {
  foo(): void;
}

@Service(ServiceAToken)
export default class ServiceAImpl implements IServiceA {
  foo() {
    console.log('ServiceAImpl.foo');
  }
}
```

```ts
// ServiceB.ts
import { Inject, Service } from 'typedi';
import { IServiceA } from './ServiceA';
import { ServiceAToken, ServiceBToken } from './tokens';

export interface IServiceB {
  bar(): void;
}

@Service(ServiceBToken)
export default class ServiceBImpl implements IServiceB {
  constructor(@Inject(ServiceAToken) private readonly serviceA: IServiceA) {}

  bar() {
    console.log('ServiceBImpl.bar');

    this.serviceA.foo();
  }
}
```

```ts
// index.ts
import 'reflect-metadata';
import Container from 'typedi';
import { IServiceB } from './ServiceB';
import { ServiceBToken } from './tokens';

const app = Container.get<IServiceB>(ServiceBToken);

app.bar();
```

</details>

so I basically was expecting that since `ServiceA` and `ServiceB` have been registered with their tokens, they'll be in the `Container` when I run `index.ts` - right? oh...

```
ServiceNotFoundError: Service "ServiceB" was not found, looks like it was not registered in the container. Register it by calling Container.set before using service.
```

Okay, no problem I thought - I'll just register them with `Container.set(...)`

<details>
<summary>Code example 2</summary>

```ts
// index.ts
import 'reflect-metadata';
import Container from 'typedi';
import { ServiceAToken, ServiceBToken } from './tokens';
import ServiceBImpl, { IServiceB } from './ServiceB';
import ServiceAImpl from './ServiceA';

Container.set([
  { id: ServiceAToken, value: ServiceAImpl },
  { id: ServiceBToken, value: ServiceBImpl },
]);

const app = Container.get<IServiceB>(ServiceBToken);

app.bar();
```

</details>

and run again...

```TypeError: app.bar is not a function```

eh? Oh is it because they're not `new`ed I thought, so I changed the `.set` to

<details>
<summary>Code example 3</summary>

```ts
// index.ts
Container.set([
  { id: ServiceAToken, value: new ServiceAImpl() },
  { id: ServiceBToken, value: new ServiceBImpl() }, // <--- ts error: Expected 1 arguments, but got 0
]);
```

</details>

However despite [the example in the docs](https://docs.typestack.community/typedi/v/develop/#typescript-usage) (3rd example down with `Container.set([...])` doesn't work for this case because `ServiceBImpl` expects 1 argument (`ServiceA` via injection).

Okay... so maybe I should modify `ServiceB` to not inject via the constructor?

<details>
<summary>Code example 3</summary>

```ts
// ServiceB.ts
@Service(ServiceBToken)
export default class ServiceBImpl implements IServiceB {

  // note that it has to have the ! otherwise there's a typescript error:
  // "Property 'serviceA' has no initializer and is not definitely assigned in the constructor"
  @Inject(ServiceAToken) private readonly serviceA!: IServiceA;

  bar() {
    console.log('ServiceBImpl.bar');

    this.serviceA.foo();
  }
}
```

</details>

Annnnd run...

```sh
> ServiceBImpl.bar # our console.log from ServiceB.bar()
> ServiceB.js:17
>         this.serviceA.foo();
>                       ^
> TypeError: Cannot read property 'foo' of undefined
```

Okay, so now it's successfully calling `ServiceBImpl.bar()` ... but `ServiceA` wasn't injected to `ServiceB`

🤔 I'm thoroughly stuck now... let's put a hold on this for a second.

# The problem

The reason for following this pattern is so that when I test I don't have to use the `Impl` class. If I follow the easiest way to use typedi (as most of the examples show, where you inject without the `@Inject` and let the reflection manage it) when I go to mock a service with other injections in the constructor I have to do casting `as any` to quiet down ts - but this suppresses interface implementation issues which is exactly what I want by using the interfaces and implementations.

# The solution (that I found)

Okay, so somehow I stumbled across using a function that returns the `Impl` inside the `@Inject` - I think I noticed it when looking at the types for `@Inject`, it may have also been glanced at on a page in the old/new documentation ...?

So, with a few changes like so

<details>
<summary>Code example 4</summary>

```ts
// tokens.ts (deleted, not required anymore)
```

```ts
// ServiceA.ts
import { Service } from 'typedi';

export interface IServiceA {
  foo(): void;
}

@Service()
export default class ServiceAImpl implements IServiceA {
  foo() {
    console.log('ServiceAImpl.foo');
  }
}
```

```ts
// ServiceB.ts
import { Inject, Service } from 'typedi';
import ServiceAImpl, { IServiceA } from './ServiceA';

export interface IServiceB {
  bar(): void;
}

@Service()
export default class ServiceBImpl implements IServiceB {

  // Notice how the @Inject is being used here, but the class constructs with the interface...?
  // this solves the issue when testing that you don't need to implement the class or cast, just match the interface
  constructor(@Inject(() => ServiceAImpl) private readonly serviceA: IServiceA) {}

  bar() {
    console.log('ServiceBImpl.bar');

    this.serviceA.foo();
  }
}
```

```ts
// index.ts
import 'reflect-metadata';
import Container from 'typedi';
import ServiceBImpl from './ServiceB';

const app = Container.get(ServiceBImpl);

app.bar();
```

</details>

and volia... it works as expected.

```sh
> ServiceBImpl.bar
> ServiceAImpl.foo
```

The only downside being that the token constants are no longer there/required - but imo that's a small price to pay for having the pattern seemingly working as I first expected.

# The questions (finally)

* Is this the intended way to use the framework? I didn't find it explicitly documented this way in one place - but it works
* Am I doing anything wrong using it this way? Will something unexpected happen at scale or something I can't see?
* Can this pattern of use be more clearly documented end to end? IMO Tokens do not work the way that they appeared to work/work in other frameworks (e.g. I've seen this implemented with I think `tags` in an `inversify` project)

If you took the time to read this, thanks... hope it helps you.

**Comment by pyrrhicman** [comment]
> Hi there, this is a bit more of an explanation of my journey with the hope that maintainer and/or other users will find this useful.
> 
> After spending a few hours on trying to work out what I was doing wrong, I finally cracked it and I believe its due to a few misconceptions I maybe have picked up from the documentation.
> 
> Related: #79
> 
> # I was trying to...
> I was trying to implement a rough DDD pattern in my application using typedi. I thought that because typedi provides the `Token` class, I could something along the lines of the following (please note that these are all different files, which may contribute to the problem? I suspect it might work if you place these all in a single file... also note that I've tried to break it down to the smallest reproduction possible)
> 
> Code example 1
> so I basically was expecting that since `ServiceA` and `ServiceB` have been registered with their tokens, they'll be in the `Container` when I run `index.ts` - right? oh...
> 
> ```
> ServiceNotFoundError: Service "ServiceB" was not found, looks like it was not registered in the container. Register it by calling Container.set before using service.
> ```
> 
> Okay, no problem I thought - I'll just register them with `Container.set(...)`
> 
> Code example 2
> and run again...
> 
> `TypeError: app.bar is not a function`
> 
> eh? Oh is it because they're not `new`ed I thought, so I changed the `.set` to
> 
> Code example 3
> However despite [the example in the docs](https://docs.typestack.community/typedi/v/develop/#typescript-usage) (3rd example down with `Container.set([...])` doesn't work for this case because `ServiceBImpl` expects 1 argument (`ServiceA` via injection).
> 
> Okay... so maybe I should modify `ServiceB` to not inject via the constructor?
> 
> Code example 3
> Annnnd run...
> 
> ```shell
> > ServiceBImpl.bar # our console.log from ServiceB.bar()
> > ServiceB.js:17
> >         this.serviceA.foo();
> >                       ^
> > TypeError: Cannot read property 'foo' of undefined
> ```
> 
> Okay, so now it's successfully calling `ServiceBImpl.bar()` ... but `ServiceA` wasn't injected to `ServiceB`
> 
> 🤔 I'm thoroughly stuck now... let's put a hold on this for a second.
> 
> # The problem
> The reason for following this pattern is so that when I test I don't have to use the `Impl` class. If I follow the easiest way to use typedi (as most of the examples show, where you inject without the `@Inject` and let the reflection manage it) when I go to mock a service with other injections in the constructor I have to do casting `as any` to quiet down ts - but this suppresses interface implementation issues which is exactly what I want by using the interfaces and implementations.
> 
> # The solution (that I found)
> Okay, so somehow I stumbled across using a function that returns the `Impl` inside the `@Inject` - I think I noticed it when looking at the types for `@Inject`, it may have also been glanced at on a page in the old/new documentation ...?
> 
> So, with a few changes like so
> 
> Code example 4
> and volia... it works as expected.
> 
> ```shell
> > ServiceBImpl.bar
> > ServiceAImpl.foo
> ```
> 
> The only downside being that the token constants are no longer there/required - but imo that's a small price to pay for having the pattern seemingly working as I first expected.
> 
> # The questions (finally)
> * Is this the intended way to use the framework? I didn't find it explicitly documented this way in one place - but it works
> * Am I doing anything wrong using it this way? Will something unexpected happen at scale or something I can't see?
> * Can this pattern of use be more clearly documented end to end? IMO Tokens do not work the way that they appeared to work/work in other frameworks (e.g. I've seen this implemented with I think `tags` in an `inversify` project)
> 
> If you took the time to read this, thanks... hope it helps you.

Oh man you are my HERO. I did all of that too 😭.  I was looking forward to change to inversify.io (that I don't like for now 👀) but now that I t got it fixed and NO TOKENS 🥰

Thanks for sharing in detail. I just found your solution and fixed it in 5 minutes while I struggled to implement Inversion of control for days.
🥳 I am happy

**Comment by NoNameProvided** [comment]
Hi! Thanks for the detailed report!

This seems to be a bug. Your original version should work and indeed it does if you simply `console.log` the `ServiceBImpl` class before calling `Container.get`. I suspect this is due to some changes to how the JS code is generated from Typescript.

On a side note, when testing your classes you can always create a custom container where you set the dummy implementation instead of the oringal class.

**Comment by NoNameProvided** [comment]
I have checked and indeed your initial example doesn't work because it TypeScript will cut unused imports from the final bundle. (The file will be translated to JS, but if A imports B but doesn't use it the import statement will be removed.) 

The following example will work:

<details>
<summary>Details</summary>

```ts
// index.ts
import "reflect-metadata";
import Container from "typedi";
import { ServiceBToken } from "./tokens";

/**
 * Import the module for it's side-effetcs, aka the code is run,
 * and the `@Service` decorators register the two services in the Container.
 *
 * If we would use the import { ServiceAImpl } from './ServiceA'; format but doesn't use the class definition
 * TypeScript would remove that import statement.
 */
import "./ServiceB";
import "./ServiceA";

const app = Container.get(ServiceBToken);

app.bar();
```

```ts
// tokens.ts
import { Token } from "typedi";
import { ServiceBImpl } from "./ServiceB";
import { ServiceAImpl } from "./ServiceA";

/** I have fixed the return type for you in your tokens. They will reference the service implementations, not  a string. */
export const ServiceAToken = new Token<ServiceAImpl>("ServiceA");
export const ServiceBToken = new Token<ServiceBImpl>("ServiceB");
```

```ts
// serviceA.ts
import { Service } from "typedi";
import { ServiceAToken } from "./tokens";

export interface IServiceA {
  foo(): void;
}

@Service(ServiceAToken)
export class ServiceAImpl implements IServiceA {
  foo() {
    console.log("ServiceAImpl.foo");
  }
}
```

```ts
// serviceB.ts
import { Inject, Service } from "typedi";
import { ServiceAImpl } from "./ServiceA";
import { ServiceAToken, ServiceBToken } from "./tokens";

export interface IServiceB {
  bar(): void;
}

@Service(ServiceBToken)
export class ServiceBImpl implements IServiceB  {
  constructor(@Inject(ServiceAToken) private readonly serviceA: ServiceAImpl) {}
  bar() {
    console.log("ServiceBImpl.bar");
    this.serviceA.foo();
  }
}
```

</details>

This behavior will be added to the documentation.

**Comment by NoNameProvided** [comment]
> Is this the intended way to use the framework? I didn't find it explicitly documented this way in one place - but it works

Your initial attempt is how the library should be used. 

There are two ways you can register dependencies in a container:

- via the `@Service` decorator
- via explicitly calling `Container.set`, there are two sub-method to use with Container.set
  - calling `Container.set({ id: <MY-IDENTIFIER>, value: <MY-VALUE> })`
  - calling `Container.set({ id: <MY-IDENTIFIER>, type: <MY-CONSTRUCTABLE-TYPE> })`
  
When you set the **`value`** in the container, you tell TypeDI that when you request the given ID you want that explicit value you have set. When you set the **`type`** in the container, you tell TypeDI that create an instance of this constructable (class) when I request this ID first and then always return the same created value (except if `transient: true` is set).

When registering a service via the `@Service` decorator you don't need to set the same type via the `Container.set` method. However, your class definition must be imported into the application before requesting it from the Container. Eg:

```ts
import 'my-class-definition.ts';
```

Obviously, if your code is not imported in the application, then the `@Service` decorator is never executed and the class will be never registered in the default container.

> Am I doing anything wrong using it this way? Will something unexpected happen at scale or something I can't see?

No, even your last example is fine. It's just doesn't required to provide the Inject decorator on constructor parameters, but if you do it won't do harm.

> Can this pattern of use be more clearly documented end to end? IMO Tokens do not work the way that they appeared to work/work in other frameworks

Yes, the documentation will be updated.

**Comment by South-Paw** [comment]
@NoNameProvided thank you for the great response! :)
