### ISSUE TITLE
feature: option for eager service instantiation

### ISSUE THREAD

**Issue by cburnicki** [typestack/typedi#149]
### Description
Currently, services are lazy instantiated. There might be a good reason for this (i.e. lower application startup time), but in some cases, there are some negative implications to this.

One example: In combination with routing-controllers, a controller and its dependencies are not instantiated on startup. If, for example, a wrong configuration causes a service to fail to connect to a database or find a directory, this would only be noticed once a request to the corresponding route is made. I usually prefer a fail-fast approach that would cause my application to crash on startup or shortly after.

Another reason for an eager service instantiation option could be to have "hot" routes as soon as the application reached a steady state. Currently, the first call to an endpoint can cause a noticeable delay (i.e. in test) in larger app with lots of service dependencies.

Currently this can be achieved by calling `Container.set()` with a service instance but this seems to be a bit cumbersome, especially in combination with routing-controllers.

### Proposed solution
I think it would be really nice to have an option to enable eager service instantiation in typedi, so every imported service will be instantiated immediately.

**Comment by exejutable** [comment]
+1 to this proposal

**Comment by NoNameProvided** [comment]
Done in a25c98026450468eef37c0c46e775dacab62d97e.
