### ISSUE TITLE
feature: Support Symbol as service id

### ISSUE THREAD

**Issue by dilame** [typestack/typedi#197]
Not sure why it's not supported yet.

https://github.com/typestack/typedi/blob/develop/src/types/service-identifier.type.ts

**Comment by theodorDiaconu** [comment]
Basically this is the natural "Token". It's unique in the sense it cannot collide, and it has a name. Currently we can use Tokens I don't mind.

**Comment by NoNameProvided** [comment]
What is the advantage of using it instead of `Tokens`? The "problem" with adding this is that it needs custom error handling to write proper error messages. So does the usage of Symbols give you some advantage over Tokens?

**Comment by NoNameProvided** [comment]
I tested if it can be added easily and it cannot, it breaks some assumptions as Symbol doesn't have a prototype exposed and we check for that. I would rather keep the inner working simple, so I will go ahead and close this as wontfix. If this is something that breaks your workflow and your use-case __cannot__ work without symbols, then let me know and we will reopen to discuss further.
