### ISSUE TITLE
question: ServiceNotFound Error in typedi 0.10 (it worked in 0.8.x)

### ISSUE THREAD

**Issue by hieroshima** [typestack/typedi#198]
Hi,

I have a problem with tests and new version of typedi. I have an service:

```node
@Service()
export class S3Service {
  @Inject()
  private s3: S3;
```
and I want test this service. In previous version 0.8 I had working test defined like that:

```node
describe('S3Service', () => {
    let s3Params: any;
    let s3: S3;
    let s3Service: S3Service;

    beforeEach(() => {
      s3 = Container.get(S3);
      s3Service = Container.get(S3Service);
    });

    afterEach(() => {
      Container.reset();
    });

[... tests definitions here ]
```
Now, in the 0.10 version I see that kind of error:
```
ServiceNotFoundError: Service with "<UNKNOWN_IDENTIFIER>" identifier was not found in the container. Register it before usage via explicitly calling the "Container.set" function or using the "@Service()" decorator.
```
Can someone point me what changed in the 0.10 that caused this problem?

Thanks in advance.

**Comment by kirrie** [comment]
Check this [changes](https://github.com/typestack/typedi/blob/develop/CHANGELOG.md#090---20210110).
Newer version won't resolve unregistered types.

**Comment by hieroshima** [comment]
> Check this [changes](https://github.com/typestack/typedi/blob/develop/CHANGELOG.md#090---20210110).
> Newer version won't resolve unregistered types.

What does exactly mean in my example? I thought that `@Service()` mean that the type is registered?

**Comment by hieroshima** [comment]
Let's simplify it - I have that code

```node
import {S3} from 'aws-sdk';

let s3: S3;

s3 = Container.get(S3);
return;
```
I'm getting the same error where on 0.8 I got S3 class from aws-sdk - what I'm now supposed to do, to have working DI and get S3 instance in my s3 variable?

**Comment by NoNameProvided** [comment]
> I'm getting the same error where on 0.8 I got S3 class from aws-sdk - what I'm now supposed to do, to have working DI and get S3 instance in my s3 variable?

You have to register it first in the container:
```js
import {S3} from 'aws-sdk';

Container.set({ id: S3, type: S3 });

let s3: S3;

s3 = Container.get(S3);
return;
```

> What does exactly mean in my example? I thought that `@Service()` mean that the type is registered?

The `@Service` decorator register your class (`S3Service`) in the container, not the S3 class from the AWS SDK.

**Comment by hieroshima** [comment]
Thanks, @NoNameProvided -- that works now :). It seems that all objects from aws-sdk need be done in that way.
