### ISSUE TITLE
fix: Class member injection fail

### ISSUE THREAD

**Issue by kirrie** [typestack/typedi#199]
### Description
typedi: 0.8.0 ~ 0.10.0
typescript: 3.8.3
nodejs: 12.15

```ts
const TOKEN_A = new Token();
Container.set(TOKEN_A, 'token_a');

const TOKEN_B = new Token();
Container.set(TOKEN_B, 'token_b');

@Service()
class SampleA {
	@Inject(TOKEN_A)
	private tokenA: string;

	@Inject(TOKEN_B)
	private tokenB: string;

	public text: string;

	constructor() {
		this.text = `${this.tokenA}-${this.tokenB}`;
	}
}

@Service()
class SampleB {
	public text: string;

	constructor(
		@Inject(TOKEN_A) private tokenA: string,
		@Inject(TOKEN_B) private tokenB: string
	) {
		this.text = `${this.tokenA}-${this.tokenB}`;
	}
}
```

### Expected behavior
Both of services has a same text member, "token_a-token_b".

### Actual behavior
Only SampleB service has a "token_a-token_b" text member. SampleA "undefined-undefined"

**Comment by kirrie** [comment]
I think this actually occurs only when trying to use injected instance in constructor.

**Comment by magicmatatjahu** [comment]
@kirrie When you inject tokens in properties, then they are injected after constructor call (instance initialization). It's not a bug in TypeDI :)

**Comment by kirrie** [comment]
@magicmatatjahu Many thanks!
