### ISSUE TITLE
fix: 0.10.0 cannot be used in browsers

### ISSUE THREAD

**Issue by theodorDiaconu** [typestack/typedi#207]
I'm currently on 0.8.0 with my framework (kaviarjs.com) the reason being that last time I tried 0.10.0, it didn't work well on frontend and I had a lot of weird errors that didn't have time to debug. But, my question stands, is this package MEANT to work on frontend or it's only focused on backend ?

**Comment by NoNameProvided** [comment]
Yes, it should, what errors are you facing?

**Comment by theodorDiaconu** [comment]
I think it was related to the mandatory @service on classes. Will reopen when I have concrete details.
