### ISSUE TITLE
fix: passing params to transient services is not type-safe

### ISSUE THREAD

**Issue by papermana** [typestack/typedi#226]
### Description
I'm trying to create a class that accepts some params in its constructor but also still uses injected services. [This issue](https://github.com/typestack/typedi/issues/127) helped me figure out how to use transient services for this purpose. The API is a bit wonky, but OK, it works.

However, it only works as long as you consistently set the correct type as the param's value. There is nothing to warn you if your types are mismatched. Of course, that goes against the point of using Typescript, which is why I'm marking it as a bug.

**Minimal code-snippet showcasing the problem**
https://codesandbox.io/s/typedi-transient-classes-type-unsafe-9jq2g?file=/src/index.ts

This is based on the example from https://github.com/typestack/typedi/issues/127#issuecomment-667439388. The only change is that `YourService` now has a public field `foo` of type `string`. But if you run the code, you will see that `serviceInstanceB.foo` is a number.

### Expected behavior
There is a type-safe way to pass or set params for transient services.

### Actual behavior
When setting dynamic params using tokens, there is no type safety at all.

From what I can tell, there is one a definition for `set` that would enforce type safety when using tokens:
```ts
 set<T = unknown>(token: Token<T>, instance: T): this;
 ```
 
 But because there are so many overloads, Typescript ends up treating our code as
 ```ts
 ContainerInstance.set<Foo>(token: ServiceIdentifier<unknown>, instance: Foo): ContainerInstance
 ```

**Comment by NoNameProvided** [comment]
Thanks for the report. This is fixed in https://github.com/typestack/typedi/commit/940e89df74252e1dd40757a8492963cf3416b68a and will be included in the next release.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/4706265/108627474-10098180-7456-11eb-98cf-d12ad6a08f3c.png)


</details>

**Comment by papermana** [comment]
That's great, thank you!
