### ISSUE TITLE
question: injected value is ContainerInstance instead of service

### ISSUE THREAD

**Issue by herbertpimentel** [typestack/typedi#227]
I am  trying following the simple typegraphql example, but using it as handle inside of nextjs app.

**The problem:**
Everytime I am injecting the service it comes to me as "ContainerInstance"  instead of the specific service

![image](https://user-images.githubusercontent.com/1668448/108283391-f8827e00-7161-11eb-85f2-57a84d9b4158.png)

Here is a public repo to with this https://github.com/herbertpimentel/supersimples

So what I am possible doing wrong ?!

**Comment by NoNameProvided** [comment]
The container instance is always injected as the last extra parameter to allow the lib to work with JS where there are no decorators. 

I see two possible reasons: 
 - first, you are not importing `reflect-metadata` in the very first line of your code that can cause problems
 - second, I don't see any `Container.get` call, you need to request the service from the container to auto-inject the dependenciesttps://github.com/typestack/typedi#basic-usage)
 
Both of these concepts have examples in the project readme: https://github.com/typestack/typedi

**Comment by herbertpimentel** [comment]
@NoNameProvided Thanks for the quick reply, 

`reflect-metadata` is being called on the /page/api/graphql.ts this will be the very first file to be loaded on this api. 

and the call for `Container.get` should be made by the typegraphql as specified in here https://typegraphql.com/docs/dependency-injection.html

The main difference I see from my code `apollo-server-micro` to the example `apollo-server`  its uses a differente package for the server

**Comment by NoNameProvided** [comment]
This is an issue with how your app is built. It seems the meta-information about the parameter types are stripped by `next build`,

It should have meta data applied like this:
![Screenshot 2021-02-18 185625](https://user-images.githubusercontent.com/4706265/108400267-4effc300-721b-11eb-83c6-2de0b9897dd1.jpg)

but your build version looks like this:

![Screenshot 2021-02-18 185804](https://user-images.githubusercontent.com/4706265/108400322-5de67580-721b-11eb-912b-149e59e48ff1.jpg)

I cannot help with this sorry. You are probably best of asking this on the Next repo. Your question should be about how to config the build process to preserve the emitted type information by Typescript.

**Comment by herbertpimentel** [comment]
Now you that you told me that metadata has been stiped off by nextjs. I could fix that.

> Next.js does not use TSC (the original TypeScript compiler) and instead relies on Babel's @babel/preset-typescript package. Because of that, those tsconfig.json tweaks (to keep metadata on objects) do not have any effect.
> 
> Instead, I added custom Babel configuration in my Next.js project and included the equivalent options for Babel

```
{
  "presets": [
    [
      "next/babel",
      {
        "class-properties": {
          "loose": true
        }
      }
    ]
  ],
  "plugins": [
    "babel-plugin-transform-typescript-metadata",
    ["@babel/plugin-proposal-decorators", { "legacy": true }]
  ]
}

```


For future reference https://dev.to/unframework/getting-typeorm-to-work-with-next-js-and-typescript-1len

**Comment by NoNameProvided** [comment]
Glad it worked out. I am adding the docs label as this can be useful for many.
