### ISSUE TITLE
question: Documentation about `@Service` decorator

### ISSUE THREAD

**Issue by jorgemrisco** [typestack/typedi#236]
### Description
<img width="1235" alt="image" src="https://user-images.githubusercontent.com/61189874/109013132-8cd46f80-7691-11eb-891d-85185b5e3c3d.png">

### Expected behavior
I feel like we should have something written on that page about the _Service_ decorator..

### Actual behavior
https://docs.typestack.community/typedi/02-basic-usage-guide/04-service-decorator

________________
https://github.com/typestack/typedi/blob/master/docs/typescript/04-service-decorator.md

**Comment by NoNameProvided** [comment]
The rewrite of the documentation is in progress. In the meantime you can read minimal information about it in the `Old documentation` section.
