### ISSUE TITLE
question: how create singletons?

### ISSUE THREAD

**Issue by davidmoshal** [typestack/typedi#239]
### Description

This library doesn't appear to have an @Singleton annotation, and the documentation doesn't appear to have an example of how to use/enforce singletons.   

### Expected behavior

DI library either has an @Singleton annotation, or documentation on it's own magical incantations for Singletons.

**Comment by NoNameProvided** [comment]
Every service registered by default is a singleton. If you want to create a service each time is requested, you can use `transient` option when registering the service.
