### ISSUE TITLE
question: When can I use `@Optional` decorators?

### ISSUE THREAD

**Issue by Seemspyo** [typestack/typedi#252]
Hi. I do love to implement `typedi` in my project but I need something like `@Optional()`.
I found consensus #60(which wrote in 5/2018), but it seems `@Optional()` is not included yet but throwing error on null injection does.

Is there any workarounds for optional dependencies? I tries to search every docs without any luck.

**Comment by NoNameProvided** [comment]
Yes, currently we throw when requesting a non-existing token. This is the expected behavior. 

> Is there any workarounds for optional dependencies? I tries to search every docs without any luck.

There is none currently.
