### ISSUE TITLE
question: typedi not working with vite

### ISSUE THREAD

**Issue by rootsher** [typestack/typedi#253]
### Description
I would simply like to inject (via the constructor) one service into another.

**Minimal code-snippet showcasing the problem**
```ts
import "reflect-metadata";

import { Container, Service } from "typedi";

@Service()
export class AccessTokenService {
  public setToken() {}
}

@Service()
export class AuthService {
  constructor(public accessTokenService: AccessTokenService) {}
}

const authService = Container.get<AuthService>(AuthService);

// occurs: ContainerInstance {services: Array(2), id: "default", has: ƒ (), get: ƒ (), getMany: ƒ ()…}
// ...not: AccessTokenService {constructor: Object}
console.log(authService.accessTokenService);

try {
  authService.accessTokenService.setToken();
} catch (e) {
  // TypeError: authService.accessTokenService.setToken is not a function
  console.log(e);
}
```

### Expected behavior
Correctly call the setToken function.

### Actual behavior
```
TypeError: authService.accessTokenService.setToken is not a function
```

Dependencies:
* reflect-metadata - 0.1.13
* typedi - 0.10.0
* vite - 1.0.0-rc.13 (and 2.0.1 also)

Code snippets:
vite (not working) - https://codesandbox.io/s/vite-typedi-not-working-3kp45?file=/src/main.ts
parcel (working) - https://codesandbox.io/s/typedi-poyeq?file=/src/main.ts

**Comment by rootsher** [comment]
@NoNameProvided any ideas?

**Comment by NoNameProvided** [comment]
This is most likely an issue with how Vite builds your project. We rely on metadata generated by Typescript but it either is not generated at all or stripped by the build process in Vite. You should see stuff like this in the compiled JS code: https://github.com/typestack/typedi/issues/227#issuecomment-781530016

**Comment by rootsher** [comment]
Problem solved with `vite-plugin-ts` (https://www.npmjs.com/package/vite-plugin-ts) module which uses official TypeScript compiler.

vite.config.ts:
```ts
import { defineConfig } from 'vite';
import eslint from '@rollup/plugin-eslint';
import reactRefresh from '@vitejs/plugin-react-refresh';
import ViteTS from 'vite-plugin-ts';
import { resolve } from 'path';

// https://vitejs.dev/config/
export default defineConfig({
  server: {
    hmr: { overlay: false },
  },
  resolve: {
    alias: {
      '~': resolve(__dirname, 'src'),
    },
  },
  plugins: [
    {
      ...eslint({ include: 'src/**/*.+(js|jsx|ts|tsx)' }),
      enforce: 'pre',
    },
    reactRefresh(),
    ViteTS(),
  ],
});
```

babel.config.js:
```js
module.exports = {
  presets: [
    '@babel/preset-env',
    '@babel/preset-react',
    '@babel/preset-typescript'
  ],
};
```
