### ISSUE TITLE
question: there is a problem with loading the service from the node.js project, not from the typescript.

### ISSUE THREAD

**Issue by alanlee8421** [typestack/typedi#280]
```js
const AlanService = require('../../services/alan/alan.service');
const Container = require('typedi').Container;

exports.readAll = async (req, res, next) => {
  try {
    const alanService = Container.get(AlanService);
    const result = await alanService.alan();
    responseJson(req, res, result);
  } catch (error) {
    console.error(error);
    errorHandler(req, res, error, next);
  }
};
```

error log:
```
ServiceNotFoundError: Service with "MaybeConstructable<AlanService>" identifier was not found in the container. Register it before usage via explicitly calling the "Container.set" function or using the "@Service()" decorator.
```

This error occurs after version 0.8.0.

**Comment by NoNameProvided** [comment]
Hi! 

This is the expected behavior. You need to register the services first before requesting them.

**Comment by alanlee8421** [comment]
> 안녕!
> 
> 이것은 예상 된 동작입니다. 서비스를 요청하기 전에 먼저 서비스를 등록해야합니다.

**Comment by alanlee8421** [comment]
> Hi!
> 
> This is the expected behavior. You need to register the services first before requesting them.

Your guide explains that when a service is used as above, it checks for the existence of an instance and creates or retrieves it when .get is called. And the above code worked normally until 0.8.0. Can you explain how the usage has changed from the next version?

**Comment by alanlee8421** [comment]
<img width="1205" alt="스크린샷 2021-04-01 오후 12 36 09" src="https://user-images.githubusercontent.com/78144034/113240067-e3fbde80-92e6-11eb-94af-38f916fe2ef7.png">


Your official document also doesn't work.

**Comment by NoNameProvided** [comment]
That JS docs is outdated, it was just copied from the README to prevent loosing it. I will remove it altogether probably. The JS version never worked properly as most of the feature were missing because of lack of reflection which is used by the app for everything.
