### ISSUE TITLE
question: how can I know ContainerInstance exists

### ISSUE THREAD

**Issue by clwmem** [typestack/typedi#364]
**I was trying to...**
I want to reset the container only if the container instance exists.
```ts
import Container from 'typedi'

const container = Container.of('test')
if (Container.has('test')) {
  Container.of('test').reset()
} 
```

**The problem:**
Container.has method check excepted ContainerInstance 
how can I know ContainerInstance exists

**Comment by NoNameProvided** [comment]
You can use `ContainerRegistry.hasContainer()` method to check if a container exists or not.
