### ISSUE TITLE
question: Service injection into another Service

### ISSUE THREAD

**Issue by ikit** [typestack/typedi#376]
**I was trying to...**
Hi, I'm trying to use `@Service` and auto injection in a big project. There is a lot of Service and some of them need others.
It's working fine when the services are referenced in the constructor of Controllers by example.
But when I need to reference a service in the constructor of an other service, I got `undefined` (but not always... only for some of them it's not working...)

I'm wondering if there is somewhere a doc that explain deeply what is possible or not to do with `@Service` and auto injection in constructor. The doc I found on the web is ligth on talk only on quick/simple example. What about service injection into an other service, or how to manage properly circular depency and the priorities/order of instanciations ?

**Comment by NoNameProvided** [comment]
What you are experiencing is most probably due to cyclic dependencies. (Without concrete example I can guess only.) This is expected behavior, you should avoid cyclic dependencies. This topic is on my radar, it will be probably solved sometime in the distant future.

**Comment by jp-ch** [comment]
I have the same problem:

I have Services A, B, C and D. 

File 1:
```
Service()
class A {
    // some logic here
}
```

File 2:
```
Service()
class B {
    constructor(private a : A) { }
    // some logic here
}
```

File 3:
```
Service()
class C {
    constructor(private a : A, private d : D) { }
    // some logic here
}
```

File 4:
```
Service()
class D {
    constructor(private b : B) { }
    // some logic here
}
```

So there are no circular dependencies, if i understand this correctly. But in Service C i get undefined for the Service D. I think it's a question about the order of the initialization of the services. Are there any possibilities to solve this problem?
