### ISSUE TITLE
Constructor inject not working 

### ISSUE THREAD

**Issue by ibox4real** [typestack/typedi#40]
Hei, i'm experiencing weird behaviour in my tests with constructor injects

```javascript
//..
import {Container} from 'typedi';
import {AccessTokenService} from 'src/authentication/services/access-token-service';
import * as cfg from 'src/application/config';
Container.set('cfg.auth.jwt',cfg.auth.jwt);
const accessTokenService = Container.get(AccessTokenService);
accessTokenService.makeAccessToken(user);
//..
```

Dependecies are undefined when i configure them in the constructor
```javascript

import {Service, Inject, Require} from 'typedi';
// ..
@Service('AccessTokenService')
export class AccessTokenService {

    constructor(
        @Require('moment') private moment,
        @Require('jsonwebtoken') private jsonwebtoken,
        @Inject('cfg.auth.jwt') private jwt
    ) {}

    makeAccessToken(user: User) {
        console.log(typeof this.jsonwebtoken); //undefined
        console.log(typeof this.jwt); //undefined
        console.log(typeof this.moment); //undefined
        // ...
    }
}
```

But this works
```javascript

import {Service, Inject, Require} from 'typedi';
// ..
@Service('AccessTokenService')
export class AccessTokenService {

    @Require('moment') private moment;
    @Require('jsonwebtoken') private jsonwebtoken;
    @Inject('cfg.auth.jwt') private jwt;
  
    makeAccessToken(user: User) {
        console.log(typeof this.jsonwebtoken); //object
        console.log(typeof this.jwt); //object
        console.log(typeof this.moment); //function
        // ...
    }
}
```

**Comment by pleerock** [comment]
Its strange that second is case is working  it shall not work as well. Probably second case is a bug.

Your problem is that you mark service with a label, you need to call:

```ts
const accessTokenService = Container.get<AccessTokenService>('AccessTokenService'); // string here is a name of the service you provided in the decorator
accessTokenService.makeAccessToken(user);
```

instead of what you are doing right now. If you want to get service by a class then you need to remove service's label.

**Comment by ibox4real** [comment]
Thank you. As i see the type variable must be supplied when using get with string aliases.

**Comment by ibox4real** [comment]
I'm afraid this solution ```Container.get<AccessTokenService>('AccessTokenService')``` still does not inject the services into the constructor. I even removed the ```Require``` decorator and replaced it with ```Inject```. 

What am i missing here?

```javascript
import {Container} from 'typedi';
import {AccessTokenService} from 'src/authentication/services/access-token-service';
import * as cfg from 'src/application/config';
import * as moment from 'moment';
import * as jsonwebtoken from 'jsonwebtoken';

Container.set('cfg.auth.jwt', cfg.auth.jwt);
Container.set('moment', moment)
Container.set('jsonwebtoken', jsonwebtoken);
const accessTokenService = Container.get<AccessTokenService>('AccessTokenService');
```
Again, this does not work
```javascript
import {Service, Inject} from 'typedi';
//..

@Service('AccessTokenService')
export class AccessTokenService {

    public constructor(
        @Inject('moment') private moment,
        @Inject('jsonwebtoken') private jsonwebtoken,
        @Inject('cfg.auth.jwt') private jwt
    ) {
        console.log(moment); //undefined
        console.log(jsonwebtoken);  //undefined
        console.log(jwt);  //undefined
    }
   //..
}
```

but this does

```javascript
import {Service, Inject} from 'typedi';
//..

@Service('AccessTokenService')
export class AccessTokenService {

      @Inject('moment') 
      private moment;

      @Inject('jsonwebtoken')
      private jsonwebtoken;

      @Inject('cfg.auth.jwt') 
      private jwt;

   //..
}
```

**Comment by NoNameProvided** [comment]
When using classes, you don't need to use `@Inject` when injecting in the constructor. You simply write:

```ts
constructor(
    private userService: UserService,
    private loyaltyService: LoyaltyService,
    private timerService: TimerService,
  ) { }
```

I don't know about using them with default exports for other modules, but why do you want to inject them at all? You can just start using them right away.

```ts
import * as moment from 'moment';
// ....

@Service('AccessTokenService')
export class AccessTokenService {
   //...
   public myMethod() {
      return moment().format();
   }
}
```

**Comment by ibox4real** [comment]
> When using classes, you don't need to use @Inject when injecting in the constructor. You simply write:

In your example you are using concrete class implementations. But sometimes i also want my dependencies to be interface binded. That would not work, because there is now way to know which implementation to load. That is also why i use the service name in the `@Service` `@Inject` decorators. 

> I don't know about using them with default exports for other modules, but why do you want to inject them at all? You can just start using them right away.

I do this to make testing easier. If i want to mock out moment, it is a lot easier this way. In plain javascript i could also use rewire but this does not work well with a typescript setup.

**Comment by NoNameProvided** [comment]
> I do this to make testing easier 

That makes sense, but then cannot you do this?

```ts
constructor(
    private momment: moment = moment,
  ) { }
```

No need for dependency injections, you still can mock it.

**Comment by ibox4real** [comment]
I could to that way. 

Actually for testing this also works for me, because i can set the dependcies manually in the container 
```js
@Service('AccessTokenService')
export class AccessTokenService {

      @Inject('moment') 
      private moment;

      @Inject('jsonwebtoken')
      private jsonwebtoken;

      @Inject('cfg.auth.jwt') 
      private jwt;

   //..
}
```
My only problem is  why it works on the properties but not in the constructor. This seems like an inconsistency. It should either work with both or work with neither.

**Comment by pleerock** [comment]
@ibox4real can you please provide a demo git repo with minimal reproduction of this problem? I added test (see commit above) and it does not reproduce your issue

**Comment by pleerock** [comment]
ping @ibox4real

**Comment by ibox4real** [comment]
Yes, i will try to reproduce it in a simplified setup within the next few days.

**Comment by Nikoms** [comment]
Did you add import "reflect-metadata"; ?

**Comment by pleerock** [comment]
yeah, probably he forgot to import reflect-metadata. Closing.
