### ISSUE TITLE
Container.has()?

### ISSUE THREAD

**Issue by slavafomin** [typestack/typedi#46]
Hey!

Is there a way to check if container has an instance of the specific type w/o actually creating this instance?

E.g: `if (Container.has(CarService)) {}`.

Thanks )

**Comment by MaxFlower** [comment]
@slavafomin  Maybe `Conatiner instanceof CarService `will be enough?

**Comment by pleerock** [comment]
I already added `Container.has` method but did not publish it yet.

**Comment by MaxFlower** [comment]
@pleerock please let me show implementation

**Comment by pleerock** [comment]
Available since 0.6.1
