### ISSUE TITLE
Typescript error: Property does not exists

### ISSUE THREAD

**Issue by cedrickmandocdoc** [typestack/typedi#49]
Hi @pleerock typescript cannot build because of a property does not exists when injecting to a constructor. Here's the link of sample repository https://github.com/cedrickmandocdoc/typedi-bug

How can we prevent this typescript error with preserving types? I am aware that there is workaround but I should ask if this can be a typedi bug.

**Comment by pleerock** [comment]
You forgot to add:

```ts
import "reflect-metadata";
```

See docs.

**Comment by cedrickmandocdoc** [comment]
Hi @pleerock , I updated the sample repository and still can't compile. there is a:

typescript error property 'make' does not exist.

I am setting to true the strictNull option in tsconfig.json.

**Comment by pleerock** [comment]
can you please update to 0.7.0 and try again?

**Comment by cedrickmandocdoc** [comment]
Hi @pleerock after upgrading to 0.7.0, still can't compile.

**Comment by pleerock** [comment]
okay looks like issue in `strictFunctionTypes`, you need to set it to false. I'll need to research why we have problems when this option is used.
