### ISSUE TITLE
Providing values to the constructor/factory

### ISSUE THREAD

**Issue by terehov** [typestack/typedi#50]
Hello, 

maybe I am getting something wrong, but I am looking for a way to provide a parameter to the constructor. My use case is, that I would like to inject a logger, that should be instantiated with a module name, e.g. `const logger = new Logger('moduleX');`

That I would like to change to work like this
```
class ModuleX {

  @Inject
  private logger: Logger;

  public doSmth () {
    
    this.logger.info('log something');
  }
}
```

Obviously this is not supported and therefor I assume not a good practice, or am I missing something? 

thank you!

**Comment by pleerock** [comment]
Depend on what `logger` is. If it is a service then it should look something like this:

```ts
@Service()
export class Logger {

     constructor(@Inject("logger.name") name: string) {
     }

}

And then somewhere: 

Container.set("logger.name", "some name");
```

Else, if logger not a service then you can simply do:

```ts
Container.set(Logger, new Logger("some name"));
```

**Comment by pleerock** [comment]
Let me know if still have questions.

**Comment by terehov** [comment]
Thank you.

**Comment by atonamy** [comment]
@pleerock 
How about situation when we have to pass data dynamically from external source?
Can we do it this way?

```
@Service({factory: (data: {id: {engineType: string}}) => {
  return new Car(data.id.engineType)
}})
class Car {
  constructor (public engineType: string) {
  }
}

const dynamicDataFromExternalSource = {...more, engineType: "electric"}
const car = Container.of({engineType: dynamicDataFromExternalSource.engineType}).get(Car)
```
