### ISSUE TITLE
There is an error in README.md 

### ISSUE THREAD

**Issue by lanshunfang** [typestack/typedi#54]
I will list issues later. If anyone could help with PR, that would be nice.

**Comment by pleerock** [comment]
its a good idea to provide a PR directly with fixes of errors instead of creating an issue.

**Comment by lanshunfang** [comment]
Issue one:
![image](https://user-images.githubusercontent.com/1013667/36831117-5863112a-1d61-11e8-8b88-1951180624b0.png)

**Comment by lanshunfang** [comment]
BTW, I am too lazy, but we could build a live online playground in: https://stackblitz.com. Just fork: https://stackblitz.com/edit/angular-rxjs-playground-otj7ap?file=app%2Ftest%2Ftest.component.ts

**Comment by pleerock** [comment]
Im not lazy, I have too many things to work on. If you are using opensource tools you must have a simple understanding that people are spending their valuable time on opensource while other people use those tools for free. Those people must pay somehow and the simplest payment is to contribute to the project as well.
