### ISSUE TITLE
question: How to correctly instantiate class when getting value of token

### ISSUE THREAD

**Issue by griest024** [typestack/typedi#552]
**I was trying to...**
 
I want to set a class as the value for a token and get an instance of the class:

```ts
interface ServiceInterface {
  dothing() {}
}
const token = new Token<ServiceInterface>('TOKEN')

@Service
class Service implements ServiceInterface {
  dothing() {
    ...
  }
}

Container.set(token, Service)
const service = Container.get(token)

service.dothing()
```
 

**The problem:**

`Container.get` just returns the value set, in this case, the class itself, not the instance. I have to do `const service = Container.get(Container.get(token))` to get an instance.

It feels strange, is this the intended pattern? Can I set a factory for the token in which I can construct an instance?

**Comment by gerkirill** [comment]
I believe that you can only provide an instance along with the token when you call Container.set(). Here are type definitions of set() method accepting token as a first parameter:

```
set<T = unknown>(token: Token<T>, instance: T): this;
set<T = unknown>(token: ServiceIdentifier, instance: T): this;
```
Both accept instance as a 2nd parameter. 
Also, `Container.get(Container.get(token))` is equal to `Container.get(Service)`. But your code `Container.get(Container.get(token))` still makes sense to me as a tricky way to combine tokens with typedi ability to instantiate services automatically.

**Comment by griest024** [comment]
okay, I guess there's not a way to specify a factory for a token, e.g. `new Token('token', {factory: value => Container.get(value)})`?

**Comment by NoNameProvided** [comment]
@gerkirill is correct. If you want to provide the constructor type, you must pass in a `ServiceOptions` object instead of the token and instance parameter. 

Keep in mind this is changed on the develop already and you will be able to create services only via providing a [`ServiceOptions`](https://github.com/typestack/typedi/blob/develop/src/interfaces/service-metadata.interface.ts) interface.
