### ISSUE TITLE
getMany returning empty array

### ISSUE THREAD

**Issue by j3ddesign** [typestack/typedi#58]
I'm having an issue where `Container.getMany(TOKEN)` is returning an empty array, despite having `{id: TOKEN, multiple: true}` services in my project.

I have also tried with `@InjectMany(TOKEN)` to no avail.

Example repo with reproduction: https://github.com/j3ddesign/typedi-getMany-example

EDIT: as a sanity check I also replicated the example at https://github.com/typestack/typedi#using-service-groups - This also failed to get the services. 
I've tried looking through the source code of typedi to see if I can PR this, but currently it's a bit over my head. Would love a fix, this is a great feature

**Comment by j3ddesign** [comment]
Went diving through the samples in this repo and found that 
```
Container.import([
    BeanFactory,
    SugarFactory,
    WaterFactory,
]);
```
is missing from the readme.md - that would have been helpful to know 30 minutes ago haha

**Comment by pleerock** [comment]
As you can see from source `import` does nothing. You simply need to import (using es6 imports) your services if you want to service to be loaded and registered, otherwise file is never loaded and thus never registered.
