### ISSUE TITLE
Throw/Exit when dependency can't be resolved

### ISSUE THREAD

**Issue by bartlomiej-korpus** [typestack/typedi#60]
This is a proposal of feature. Should it get attention I can work on this.

The problem is simple, I think that when dependency can't be satisfied (either it doesn't exist or one of its own dependencies wasn't found) the DI container should exit saying it couldn't build the dependency tree or throw an error. When using string-based tokens it is easy to miss something.

Not doing that simply leads to very obscure errors where seemingly valid TS code throws random "undefined" errors in runtime.

What do you think?

**Comment by pleerock** [comment]
Let's implement it and see what issues we will run into.

**Comment by NoNameProvided** [comment]
Then a way to mark dependency as `@Optional()` should be added as well.

**Comment by bartlomiej-korpus** [comment]
@NoNameProvided good point, but what should be injected instead when dependency is optional? null or undefined?

**Comment by NoNameProvided** [comment]
I would vote for `null` as it indicates it was set to that value by purpose, while undefined can mean we just don't set anything. (Angular follows the same principle.)

**Comment by pleerock** [comment]
Not sure about `null`, really. I prefer `undefined` since null can be possible value of injected dependency while undefined more clearly tells that it is not defined

**Comment by bartlomiej-korpus** [comment]
I think undefined is better too, @NoNameProvided do you think @Optional() would be more appropiate or maybe something like @Inject(type => Type, { optional: true }).

**Comment by pleerock** [comment]
I vote for `@Optional()` since it is more elegant

**Comment by NoNameProvided** [comment]
> since null can be a possible value of an injected dependency 

You can set both `null` and `undefined` as values.

```ts
Container.set('test-undefined', undefined);
Container.set('test-null', null);
```

> Not sure about null, really. I prefer undefined since null can be a possible value of an injected dependency while undefined more clearly tells that it is not defined

I don't agree. I think a `null` value express it more, that we went looking for your dependency but found nothing. `null` is a value you can set on purpose to indicate your intent, `undefined` is a value you set or simply was nothing set, it's ambiguous so I would like to avoid it.

> do you think @Optional() would be more appropriate

I think an `@Optional()` decorator is much cleaner.

```ts
@Injectable()
constructor(
	@Optional() private myDep: MyDep,
	private myOtherDep: myOtherDep,
) {}
```

**Comment by pleerock** [comment]
> You can set both null and undefined as values.

correct, but `null` is more treated like a value then undefined. Im still for `undefined`, because it tells that dependency was **not defined**

> null is a value you can set on purpose to indicate your intent, undefined is a value you set or simply nothing was set, it's ambiguous so I would like to avoid it.

correct, and "simply nothing was set" can be possible only with `@Optional` flag, since if @bartlomiej-korpus implement what he proposes in this issue, it will not be possible to have "nothing was set" without optional decorator.

**Comment by Stradivario** [comment]
@pleerock i think you are correct! When you try to run void function it returns undefined.Same principe should be applied here.

Regards,
Kristiyan Tachev

**Comment by justinmchase** [comment]
Related to #97

**Comment by NoNameProvided** [comment]
Closing as duplicate in favor of #87.
