### ISSUE TITLE
Is it possible to use named params?

### ISSUE THREAD

**Issue by et** [typestack/typedi#64]
I really dig this library, but I'm missing named params from Javascript land (I still consider myself only at like 45% with Typescript).

If I have a service such as:

```js
@Service()
export class WebhookService {

  constructor(
    @OrmRepository() private borrowerRepository: BorrowerRepository,
    @OrmRepository() private webhookRepository: WebhookRepository,
    private client: ClientService,
    @Logger(__filename) private log: ILogger
  ) { }
```

My tests for this become clunky for instantiating:

```js
const service = new WebhookService(borrowerRepoMock, webhookRepoMock, clientServiceMock, logMock);
```

It would be nice if I could use named params so order wouldn't matter:

```js
const service = new WebhookService({
  borrowerRepo: borrowerRepoMock,
  webhookRepo: webhookRepoMock,
  clientService: clientServiceMock,
  log: logMock
});
```

Do you have any sample patterns to achieve this cleanly while still maintaining the dependency injected behavior?

**Comment by pleerock** [comment]
If you want to intialize your service this way, then imagine how class should be changed:

```ts
@Service()
export class WebhookService {

  constructor(private options: {
         borrowerRepository: BorrowerRepository,
         webhookRepository: WebhookRepository,
         client: ClientService,
         log: ILogger
  }) { }
```

There are lot of issues with such approach:

* unable to use decorators
* unable to control public/private scope of each property individually
* you have to use `this.options.borrowerRepository` for each property in your object everywhere in your class

If you want to initialize your service the clean way then you simply do:

```ts
const service = new WebhookService(
  borrowerRepoMock,
  webhookRepoMock,
  clientServiceMock,
  llogMock
);
````

this approach is better in ways then creating an object

**Comment by et** [comment]
Cool. Thanks for the response. I guess my issue was that I noticed my services getting to the point of accepting lots of parameters. Hence, using named parameters would lessen the burden of ordering.

But you do make good points. Named parameters loses a lot of great functionality so the trade off doesn't seem worth it. This feels like it might be a good compelling thing to bring to typescript devs.

Thanks again for your feedback. I've been loving all the typestack projects.
