### ISSUE TITLE
fix: Circular inject on constructor 

### ISSUE THREAD

**Issue by pvhuy84** [typestack/typedi#659]
### Inject circular on constructor get error

**My code**
```ts
@Service()
class ServiceA {
  constructor(@Inject(() => ServiceB) private serviceB: ServiceB) {}
}

@Service()
class ServiceB {
  constructor(@Inject(() => ServiceA) private serviceA: ServiceA) {}
}

```
It will get error `Maximum call stack size exceeded` at `ContainerInstance.class.ts` line 276

**Comment by jimhug034** [comment]
I have the same problem

**Comment by attilaorosz** [comment]
I think the docs are incorrect in this case. You can use property injection if you have circular references. @NoNameProvided Do you know if it was planned to support circular references in the constructor?
