### ISSUE TITLE
IE 11 support?

### ISSUE THREAD

**Issue by swymmwys** [typestack/typedi#66]
Hi.
I have a simple test project and it perfectly works in all browsers except IE11.
What do I need to do to be able to use 'typedi' in IE11? Is it possible?
I already tried to include es6-shim but it doesn't help.

Right now code is looks like this:

```ts
import "reflect-metadata";
import {Container, Service} from "typedi";
import Some from "./some";

@Service()
export default class TestClass {

    constructor(private some: Some, private some2: Some){
    }

    test1() {
        this.some.someMethod();
        this.some2.someMethod();
    }
}


Container.get<TestClass>(TestClass).test1();
```
And only in IE11 I have 'undefined' for both 'some' and 'some2' in TestClass constructor.

Thanks.

**Comment by pleerock** [comment]
I think you have to debug and try to find solution... I don't have IE11 and cannot test. Also try different approaches like using tokens with @Inject decorator

**Comment by swymmwys** [comment]
@pleerock 
Thanks for the response.
I already tried to use 'Inject' decorator on a class fields and it also doesn't work.

**Comment by pleerock** [comment]
can you please debug on ie11 and some other browser and find difference and where exactly issue is

**Comment by swymmwys** [comment]
I got it. https://stackoverflow.com/questions/6903762/function-name-not-supported-in-ie

![image](https://user-images.githubusercontent.com/17503250/39833374-88ff0dd2-53d2-11e8-8203-c36fa9676e34.png)

![image](https://user-images.githubusercontent.com/17503250/39833386-917b80ee-53d2-11e8-9b35-c5c14484e3f1.png)

**Comment by swymmwys** [comment]
@pleerock 
To make it work in IE11 we need at least (in my case) Array.find polyfil and Function.name property

**Comment by swymmwys** [comment]
I cannot be able to check all of the scenarios, but for a simple usage of a 'Service' and 'Inject' decorator 'typedi' is work well in IE11 if I included Array.find polyfill and Function.name property fix in to the bundle.

**Comment by pleerock** [comment]
> I cannot be able to check all of the scenarios, but for a simple usage of a 'Service' and 'Inject' decorators 'typedi' is working well in IE11 if I included Array.find polyfill and Function.name property fix in to the bundle.

if you got it working that its good for you. I don't think there are lot of IE11 users there and we shall include polifilled code into our codebase, so probably better if you (and users like you) do the same things as you did to get it working under IE11
