### ISSUE TITLE
Can't get the correct type from Container.get

### ISSUE THREAD

**Issue by Eronana** [typestack/typedi#67]
please see here:
![image](https://user-images.githubusercontent.com/9164153/40316541-39c21542-5d51-11e8-999a-f43df71eb7a0.png)
![image](https://user-images.githubusercontent.com/9164153/40316548-41106646-5d51-11e8-986f-82aeef35c0ae.png)

code is here:
```typescript
import 'reflect-metadata';
import { Service, Container } from 'typedi';

@Service()
class A {
  public hello() {
    return 'a';
  }
}

@Service()
class B {
  constructor (private a:A) {}
  public hello() {
    return `this.a.hello() returns ${this.a.hello()}`;
  }
}

const b1 = Container.get(B);
const b2 = Container.get<B>(B);
```

**Comment by pleerock** [comment]
![screenshot 2018-06-06 13 37 01](https://user-images.githubusercontent.com/1753397/41026729-b749cc64-698e-11e8-97fa-da52ee12539d.png)

Can you please provide more details on this issue?

**Comment by philraj** [comment]
I get the same issue when using generic classes:

```
import { Container } from 'typedi';

class GenericClass<T> {
  constructor(public value: T) {}
}

class ConcreteClass extends GenericClass<string> {}

const instance = Container.get(ConcreteClass); // instance is of type '{}'
```
Also using `"strict": true`.

**Comment by NoNameProvided** [comment]
Cannot reproduce. If the issue still persists please open a new issue and provide a minimal example (TS source code, tsconfig.json)
