### ISSUE TITLE
Quickstart guide for those using regular JavaScript with latest version of this package.

### ISSUE THREAD

**Issue by HappyZombies** [typestack/typedi#688]
The docs haven't been updated for those of us using regular JavaScript, so I'd wanna share on what to do now since the docs provided are auto of date and don't work..what so ever. 

I am making this due to the fact that I can't find anywhere on how to use this package without TypeScript, not all of us are fortunate enough to use TypeScript lol.

For a quick start do the following:

_Note: Make sure you install `reflect-metadata`, it is REQUIRED this for module now (as per the docs say of course:) )_

```js

require('reflect-metadata');
const { Container }= require('typedi');

class BeanFactory {
  create() {
    console.log("Brewing beans");
  }
}

class SugarFactory {
  create() {
    console.log("Sugar is being added.");
  }
}

class WaterFactory {
  create() {
    console.log("Water added.");
  }
}

class CoffeeMaker {
  constructor(container) {
    this.beanFactory = container.get(BeanFactory);
    this.sugarFactory = container.get(SugarFactory);
    this.waterFactory = container.get(WaterFactory);
  }

  make() {
    this.beanFactory.create();
    this.sugarFactory.create();
    this.waterFactory.create();
  }
}

// Register every class that will be in the container, note that the order does not matter unless you eager load.
// also note that we are not instantiating the class here, it will be instantiated whenever you call .get() for the first (and as such the constructor will run).
Container.set({type: CoffeeMaker, id: CoffeeMaker});
Container.set({type: BeanFactory, id: BeanFactory});
Container.set({type: SugarFactory, id: SugarFactory});
Container.set({type: WaterFactory, id: WaterFactory});

// now you can get and call the method!
const coffeeMaker = Container.get(CoffeeMaker);
coffeeMaker.make();

```

If you do not want to use  `reflect-metadata` for whatever reason, you will have to register this different. If interested let me know and I'll share the code :P

**Comment by attilaorosz** [comment]
@HappyZombies that’s a nice update on the documentation. Would you like to create a pull request to update the official documentation?

**Comment by HappyZombies** [comment]
I'll do what I can, at least for the quick start section. Also, do you happen to know if `reflect-metadata` is a hard requirement now? Cuz I wonder if we should update the package.json with a peer dependency.
