### ISSUE TITLE
Injection Not Working With Interfaces

### ISSUE THREAD

**Issue by ldiego08** [typestack/typedi#70]
Hi! 

What am I doing wrong here?

```ts
interface LoggingProvider { 
    error();
}

@Service()
class DefaultLoggingProvider implements LoggingProvider {
    error() {
        // .. logging goes here
    }
}

@Service()
class UsersService {
    constructor(private logger: LogginProvider) { }
}
```
`log` is undefined in `UsersService` unless I name it. Can TypeDI do interface injection without named services or am I missing something here?

**Comment by Stradivario** [comment]
Interfaces are not part of the compilation by default!
You cannot import interface since it is a code that just stays there for typing purposes.

**Comment by NoNameProvided** [comment]
Hey @ldiego08!

As @Stradivario wrote, interfaces are compiled away and not part of the transformed code. You need to use classes. So you need to import the `DefaultLoggingProvider`

```ts
@Service()
class UsersService {
    constructor(private logger: DefaultLoggingProvider) { }
}
```

**Comment by Skona27** [comment]
But why? What is the purpose of this, that we must provide specific class in the constructor?

`constructor(private logger: LogginProvider)` 

Isn't it in conflict with whole idea behind DI pattern?

**Comment by ikatun** [comment]
I think this can work, the compiler just needs a bit of your help :)

```
interface LoggingProvider { 
    error();
}

// This gives you a runtime handle for the interface which can't be deleted by the transpiler
// Best place to put this in the same file as your LoggingProvider interface
const LoggingProvider = class Dummy {} as any;

@Service()
class DefaultLoggingProvider implements LoggingProvider {
    error() {
        // .. logging goes here
    }
}

...
// the code where you setup the ContainerInstance
container.set(LoggingProvider, container.get(DefaultLoggingProvider))
....

@Service()
class UsersService {
    constructor(private logger: LogginProvider) { }
}

```

**Comment by NoNameProvided** [comment]
> But why? 

This is an upstream decision, it simply works this way in Typescript and we cannot do anything about it.

> I think this can work, the compiler just needs a bit of your help

No, it cannot, the interfaces are compiled away into a simple empty Object. TypeDI and neither any other library can differentiate between them.

**Comment by Stradivario** [comment]
Types in typescript are now part of the build i will try some solutions and will let you know guys.

**Comment by NoNameProvided** [comment]
I would rather not complicate things with that event if it works. (I haven't heard about it.) Just use class definitions.

**Comment by lucastschmidt** [comment]
There is a solution:

For example, I have an EmailTransporter interface ... that is injected into the EmailService, by naming the inject `@Inject('emailerTransporter')`

For my use case, this works fine.

```
@Service({ name: NAME })
export class EmailerService extends BaseService {
  @Inject('emailerTransporter')
  private emailerTransporter: EmailerTransporter;

  constructor() {
    super(NAME);
  }```

For example ... since you named the Inject ... you can ... 

```
beforeAll(() => {
  Container.set(SENDGRID_API_KEY, process.env[SENDGRID_API_KEY.name]);
  const sendGridTransporter = Container.get(SendGridTransporter);
  Container.set('emailerTransporter', sendGridTransporter);
});

describe('Send email', () => {
  it('it should send an email', async () => {
    const emailerService = Container.get(EmailerService);
    const result = await emailerService.sendEmail(
      {
        from: 'test@github.com',
        to: 'test@github.com',
        subject: 'Test Mail',
        text: 'This is an automatic test',
      },
      ctx,
    );
    expect(result.success).toEqual(true);
  });
});```
