### ISSUE TITLE
 @Inject working only in class annotated with @Service

### ISSUE THREAD

**Issue by LogeswaranAnandan** [typestack/typedi#73]
I used @Inject to inject a service within another service class and it worked. But when I tried Injecting a service class within a class annotated with @controller of 'routing-controllers' package, it didn't work.

Whereas I am able to access the singleton instance of the service using Container.get().

I wish to use @Inject in my controller for uniformity across my application. Is there any way to achieve this?

This piece of code works.

```
@Controller()
export class TestController {
constructor(private testService: TestService) {
this.testService = Container.get('test.service');
}

@Get('/')
getRequest() {
    return this.testService.getRequest();
}
}
```

```
@Service('test.service')
export class TestService {
@Inject('test.Util')
testUtil: TestUtil;

 getRequest() {
    //some operation on testUtil
 }
}
```

Where as this doesn't

```
@Controller()
export class TestController {
@Inject('test.service')
testService: TestService

@Get('/')
getRequest() {
    return this.testService.getRequest();
}
}
```

This throws an error as "cannot read property getRequest of undefined".
Can someone explain this issue?

**Comment by Luke265** [comment]
You have to set routing-controllers to use typedi with `useContainer` function. More about this: https://github.com/typestack/routing-controllers#using-di-container

**Comment by LogeswaranAnandan** [comment]
It's working. Thanks a lot!
