### ISSUE TITLE
Injection not working with Map instance as constructor parameter

### ISSUE THREAD

**Issue by petermetz** [typestack/typedi#75]
The constructor declaration

<img width="514" alt="screen shot 2018-07-26 at 10 12 55 pm" src="https://user-images.githubusercontent.com/1583231/43303319-0ed22e9c-9124-11e8-8372-0c8e7001a94d.png">

The exception thrown when Container.get(...) is called with the class passed in whose constructor you can see above:
<img width="1227" alt="screen shot 2018-07-26 at 10 11 29 pm" src="https://user-images.githubusercontent.com/1583231/43303470-c669ba7a-9124-11e8-9b4f-e8c64cc59200.png">

**Comment by fortael** [comment]
The same. Instead of class instance i got Container as first argument.

**Comment by NoNameProvided** [comment]
If you receive the Container instead of an instance that currently means you did not import `reflect-metadata` (or import it too late). I admit this is not a user-friendly UX we should throw an error in such a case.
