### ISSUE TITLE
Type injection not working at all.

### ISSUE THREAD

**Issue by mjdikun** [typestack/typedi#78]
Using Typescript, Express, TypeORM

Not even using routing-controllers, but tried adding it in after I saw the Troubleshooting guide... doesn't make any sense to have though..

No idea why it's not working, it's not even injecting App.ts into Index.ts

/home/mdikun/shopify/apps/fashion-options-ts/api/dist/index.js:45
        this.server = http.createServer(this.app.express);
                                                ^

TypeError: Cannot read property 'express' of undefined
    at new Index (/home/mdikun/shopify/apps/fashion-options-ts/api/dist/index.js:45:49)
    at ContainerInstance.getServiceValue (/home/mdikun/shopify/apps/fashion-options-ts/api/node_modules/typedi/ContainerInstance.js:207:21)
    at ContainerInstance.get (/home/mdikun/shopify/apps/fashion-options-ts/api/node_modules/typedi/ContainerInstance.js:43:25)
    at Function.Container.get (/home/mdikun/shopify/apps/fashion-options-ts/api/node_modules/typedi/Container.js:38:36)
    at Object.<anonymous> (/home/mdikun/shopify/apps/fashion-options-ts/api/dist/index.js:91:28)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**index.ts**

`import "reflect-metadata"; 
import {useContainer as routingUseContainer} from "routing-controllers";
import * as http from 'http';
import * as debug from 'debug';

import App from './App';

import {createConnection, useContainer as typeormUseContainer} from 'typeorm';
import {Container, Service, Inject} from "typedi";

typeormUseContainer(Container);
routingUseContainer(Container);
 
debug('ts-express:server');
( async function initCon(){
  //"use strict"
  console.log("createConnection()");
  try{
    const connection = await createConnection();
  }catch(e){
    console.log(e);
  }
  console.log("createConnection() done");
})();

@Service()
export class Index {
  private port = 5000;
  @Inject()
  private app: App;
  private server;
  constructor(){
    this.server = http.createServer(this.app.express);
    this.server.listen(this.port);
    this.server.on('error', this.onError);
    this.server.on('listening', this.onListening);
  }
  
  normalizePort(val: number|string): number|string|boolean {
    let port: number = (typeof val === 'string') ? parseInt(val, 10) : val;
    if (isNaN(port)) return val;
    else if (port >= 0) return port;
    else return false;
  }
  
  onError(error: NodeJS.ErrnoException): void {
    if (error.syscall !== 'listen') throw error;
    let bind = (typeof this.port === 'string') ? 'Pipe ' + this.port : 'Port ' + this.port;
    switch(error.code) {
      case 'EACCES':
        console.error(`${bind} requires elevated privileges`);
        process.exit(1);
        break;
      case 'EADDRINUSE':
        console.error(`${bind} is already in use`);
        process.exit(1);
        break;
      default:
        throw error;
    }
  }
  
  onListening(): void {
    let addr = this.server.address();
    let bind = (typeof addr === 'string') ? `pipe ${addr}` : `port ${addr.port}`;
    debug(`Listening on ${bind}`);
  }
}
let i = Container.get(Index);
export default Index;`

**App.ts**

`import * as dotenv from 'dotenv';

dotenv.config();
import * as express from 'express';
const app = express();
import * as logger from 'morgan';
import * as bodyParser from 'body-parser';

import {ShopRouter}  from './routers/shop.router';
import * as FieldRouter  from './routers/field.router';
import * as  SelectorRouter  from './routers/selector.router';
import * as OptionSetRouter  from './routers/optionset.router';
import { Service, Inject } from 'typedi';

const apiKey = "73c96e4370be5852d4d6698d303f3634";
const apiSecret = "d590ba6c963e1351a72b06ff23d4ce46";

const scopes = "write_products";

const forwardingAddress = "https://3c3039d5.ngrok.io";
 
@Service()
class App {

    public express: express.Application;

    @Inject()
    private shopRouter: ShopRouter;

    constructor(){
        this.express = express();
        this.middleware();
        this.routes();
    };

    private middleware(): void {
        this.express.use(logger('dev'));
        this.express.use(bodyParser.json());
        this.express.use(bodyParser.urlencoded({ extended: false }));
    };  
 
    private routes(): void {
        let router = express.Router();
        // placeholder route handler
        router.get('/shopify', this.shopifyRoute);
        
        this.express.use('/shops', this.shopRouter.router);
        this.express.use('/fields', FieldRouter.default);
        this.express.use('/selectors', SelectorRouter.default);
        this.express.use('/optionsets', OptionSetRouter.default);
        this.express.use('/', router);
         
    };
 
    private shopifyRoute(req: any, res:any) {
        const shop = req.query.shop;
        if(shop){
            const state = 'myuniquecookie';
            const hmac = req.query.hmac;
            console.log("Hmac: " + hmac);
            const code = req.query.code;
            console.log("Code: " + code);
            const redirectUri = forwardingAddress;
            const installUrl = 'https://'+shop+'/admin/oauth/authorize?client_id=' + 
                apiKey + 
                '&scope='+scopes+
                '&state='+state+
                '&redirect_uri='+redirectUri;
            res.cookie("state", state);
            res.redirect(installUrl);

        }else{
            return res.status(400).send("missing shop parm. Please add ?shop=your-dev-shop.myshopify.com to your request");

        }
    };
}

export default App;`

**package.json**

`{
  "name": "api",
  "version": "1.0.0",
  "description": "Fashion options api",
  "main": "express.js",
  "scripts": {
    "start": "node dist/index.js",
    "build": "gulp scripts",
    "build-watch": "gulp watch",
    "server": "nodemon dist/index.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "body-parser": "^1.15.2",
    "express": "^4.14.0",
    "gulp": "^3.9.1",
    "gulp-typescript": "^5.0.0-alpha.2",
    "morgan": "^1.7.0",
    "mysql2": "^1.6.1",
    "nodemon": "^1.17.5",
    "nonce": "^1.0.4",
    "reflect-metadata": "^0.1.12",
    "request": "^2.87.0",
    "request-promise": "^4.2.2",
    "routing-controllers": "^0.7.7",
    "typedi": "^0.8.0",
    "typeorm": "^0.2.7",
    "typeorm-typedi-extensions": "^0.2.1",
    "typescript": "^2.9.2"
  },
  "devDependencies": {
    "@types/body-parser": "0.0.33",
    "@types/debug": "0.0.29",
    "@types/express": "^4.0.33",
    "@types/morgan": "^1.7.32",
    "@types/node": "^6.0.117"
  }
}
`
**tsconfig.json**
`{
    "compilerOptions": {
      "target": "es6",
      "module": "commonjs",
      "outDir": "dist",
      "strictNullChecks": false,
      "noImplicitUseStrict" : true,
      "emitDecoratorMetadata": true,
      "experimentalDecorators": true
    },
    "include": [
      "src/**/*.ts"
    ],
    "exclude": [
      "node_modules"
    ],
    
  }`

and i'm using gulp to build app...
**gulpfile.js**
`const gulp = require('gulp');
const ts = require('gulp-typescript');
const JSON_FILES = ['src/*.json', 'src/**/*.json'];

// pull in the project TypeScript config
const tsProject = ts.createProject('tsconfig.json');

gulp.task('scripts', () => {
  const tsResult = tsProject.src()
  .pipe(tsProject());
  return tsResult.js.pipe(gulp.dest('dist'));
});

gulp.task('watch', ['scripts'], () => {
  gulp.watch('src/**/*.ts', ['scripts']);
});

gulp.task('assets', function() {
  return gulp.src(JSON_FILES)
  .pipe(gulp.dest('dist'));
});

gulp.task('default', ['watch', 'assets']);`

**Comment by montera82** [comment]
could you format your code properly  👉  https://guides.github.com/features/mastering-markdown/

**Comment by NoNameProvided** [comment]
Closing as out of date. If the issue still persists please open a new issue.
