### ISSUE TITLE
Interface and Implementation Inject Issue

### ISSUE THREAD

**Issue by knightpop** [typestack/typedi#79]
Thank you for making this wonderful library! But, I have some issue with your lib...
There is an example.
* Interface
```ts
export interface InterfaceClass {
  helloWorld(): string;
}
```
* Implementation
```ts
import {InterfaceClass} from "./InterfaceClass";
import {Service} from "typedi";

@Service('helloworld')
export class InterfaceClassImpl implements InterfaceClass {
  helloWorld(): string {
    return 'Hello World!';
  }

}
```

And I got error with this code
* Test code
```ts
import 'reflect-metadata'
import 'mocha';
import {Container} from "typedi";
import {InterfaceClass} from "./InterfaceClass";
import {InterfaceClassImpl} from "./InterfaceClassImpl";

describe('Inject test', () => {
  it('We cannot DI', () => {
    let interfaceClass: InterfaceClass = Container.get('helloworld');
    console.log(interfaceClass.helloWorld())
  });
});
```
* Error code
```
ServiceNotFoundError: Service "helloworld" was not found, looks like it was not registered in the container. Register it by calling Container.set("helloworld", ...) before using service.
    at new ServiceNotFoundError (src/error/ServiceNotFoundError.ts:11:9)
    at ContainerInstance.getServiceValue (src/ContainerInstance.ts:277:19)
    at ContainerInstance.get (src/ContainerInstance.ts:119:21)
    at Function.Container.get (src/Container.ts:107:36)
    at Context.it (source/InjectTest.ts:11:52)
```
But weirdly, I can succes when I append ```Container.get(InterfaceClassImpl);```
* Success Test Code
```ts
describe('Inject test', () => {
  it('We can DI', () => {
    Container.get(InterfaceClassImpl);
    let interfaceClass: InterfaceClass = Container.get('helloworld');
    console.log(interfaceClass.helloWorld())
  });
  it('We can DI too', () => {
    new InterfaceClassImpl();
    let interfaceClass: InterfaceClass = Container.get('helloworld');
    console.log(interfaceClass.helloWorld())
  });
});
```

`Container.get` seems to call new... I means, if we don't new, we cannot register service. What is the right way to do?

**Comment by hendratommy** [comment]
Exactly my problem, any work arround?

**Comment by openprojectio** [comment]
Seems like we need to import the all services files into the main files, after the `import "reflect-metadata"`. In my case, this was done like:

```
\\ Main.ts
import "reflect-metadata";
import { useContainer, useKoaServer } from "routing-controllers";
import { Container } from "typedi";
import "./services/PartnerABillPaymentService"; // required to work
import "./services/ParnerBBillPaymentService"; // required to work

...
```

```
\\ services/PartnerABillPaymentService.ts
import { IBillPaymentService } from "src/types";
import { Service } from "typedi";

@Service("partnerAService")
export default class PartnerABillPaymentService implements IBillPaymentService {
    ...
}

\\ services/PartnerBBillPaymentService.ts
@Service("partnerBService")
export default class PartnerBBillPaymentService implements IBillPaymentService {
    ...
}
```

```
\\ controllers/BillPaymentController.ts
import { Ctx, JsonController, Post, QueryParam } from "routing-controllers";
import { IBillPaymentService } from "src/types";
import { Container } from "typedi";

@JsonController("/bills")
export default class BillPaymentController {
	@Post("/inquiry")
    public async billInquiry(
        @Ctx() ctx: Context,
        @QueryParam("serviceName") serviceName: string
    ) {
        this.logger.info(`${ctx.request.method} ${ctx.request.path}`);

        const billPaymentService = Container.get<IBillPaymentService>(
            serviceName
        ); // it is working now

        const { billerCode, customerNo } = ctx.request.body;
        const billInquiryResult = await billPaymentService.billInquiry(
            billerCode,
            customerNo
        );

        return billInquiryResult;
    }
    ...
}
```

**Comment by vtajzich** [comment]
Any updated on it? I'm struggling with same issue. Workaround from @openprojectio doesn't work for me.

**Comment by AndKiel** [comment]
I encountered the same problem. In the end I removed the Token and started using `Container.get(ServiceClass)`. Something seems to be broken when service is being registered via `@Service({ id: MyToken }` and `Container.get` doesn't see it.

**Comment by ps2goat** [comment]
This workaround (importing services into the main file) doesn't seem to work.  I loaded up an app with version 0.8.0, and it won't work. This was working a month or so ago.  I performed an `npm ci` from my master branch, which currently works in external environments. This would make me think that maybe it's a dependency, but there are no runtime dependencies in typedi.

My current situation that I've narrowed it down to is a nested dependency like so. Each is in a different file:
```
@Service()
export class A {
  constructor(private readonly c: C) {}
}
@Service()
export class B {
  constructor (private readonly a: A) {}
}

@Service()
export class C {
  // config data
}
```

In my main startup file, I load configurations from an external source, then set them in the container:
```
const c = new C(val1, val2);
Container.set(C, c);
```

After this, my other code runs that then performs a `Container.get(B)`. This is also in a different file from main.

Here's the weird part: `A` is instantiated before any of my main code file is executed.  Thus, by the time I get to `Container.get(B)`, `A` already exists and has an empty (default new) value, which has an empty (default new) value of `C`.  `C` is supposed to have my config info in it, but it does not.  `Container.get(C)` works at this point, and returns the value I set.

Is this related, or a new issue?

**Comment by grigyenn** [comment]
The another problem is you don't want to implement methods in all you abstract inherited classes. That's why you use `interface`, because in case of `interfaces` it's not required ( impossible ) to implement parent `interface`.

To solve this problem I think `interfaces` should be compiled, but we don't know how `TypeScript` implemented, maybe it will change whole concept of this language.

**Comment by NoNameProvided** [comment]
Cannot reproduce. 

```ts
// import 'reflect-metadata';
import { Service, Container } from 'typedi';

export interface InterfaceClass {
  helloWorld(): string;
}

@Service('helloworld')
export class InterfaceClassImpl implements InterfaceClass {
  helloWorld(): string {
    return 'Hello World!';
  }
}

let instance: InterfaceClassImpl = Container.get('helloworld');

console.log(instance instanceof InterfaceClassImpl);
// returns true
console.log(instance.helloWorld());
// returns Hello World!
```

Working as intended.
