### ISSUE TITLE
Support @Inject() without params for intent communication

### ISSUE THREAD

**Issue by jasperblues** [typestack/typedi#83]
Given service: 

```ts
@Service()
export class OrganisationManager extends Object {
 // ...
}
```

And controller: 

```ts
@JsonController()
export class OrganisationController extends Object {

    constructor(@Inject() readonly organisationManager: OrganisationManager) {
        super();
        this.organisationManager = organisationManager;
    }
```

^-- Declaring `@Inject` above causes failure. It would be nice if empty inject defaults to injection by type.

**Comment by jasperblues** [comment]
It would also be nice if the contract for `@Inject()` is to inject or fail.

**Comment by NoNameProvided** [comment]
If you want to simplify your code, you can specify `@Service` on `OrganisationController`. This way you don't need to specify `@Inject` there because constructor injection is the default behavior.

```ts
import 'reflect-metadata';
import { Token, Service, Inject, Container } from 'typedi';

@Service()
class WaterFactory {
  create() {}
}

@Service()
class CoffeeMaker {
  constructor(
    private waterFactory: WaterFactory
  ) {}

  make() {
    this.waterFactory.create();
  }
}

let coffeeMaker = Container.get(CoffeeMaker);
coffeeMaker.make();
```

An empty `@Inject` will not be able to find out always what to inject.
