### ISSUE TITLE
Injecting across libraries

### ISSUE THREAD

**Issue by itonics-tbeauvais** [typestack/typedi#86]
I am wondering if you have a solution to `@Inject` from a library? We are looking to create services that are in libraries and will use typedi to wire everything up. Unfortunately, this doesn't work as the decorators are not really exported or something. Do you have any insights? Anything would be much appreciated! Cheers.

**Comment by vecernik** [comment]
I went to this issue recently trying to refactor shared code out to a npm on private git.

In npm lib (only native typescript): 
@Service()
export class Environment {

  @Inject('environments') environments: ane

  get current(): any {
    return this.environments
  }
}

In code: 
import 'reflect-metadata' // other imports redacted

Container.set('environments', {hello: true})

const env: Environment = Container.get(Environment)

console.log(env.current)  // results in undefined

Is there a way how to make TypeDI share a single container in entire project including node_modules?
