### ISSUE TITLE
Package missing a typing that declares the typedi module

### ISSUE THREAD

**Issue by silkentrance** [typestack/typedi#89]
Currently I have a hard problem with my typescript based project to import anything from the typedi module.

I am using the latest version 0.8.0 of typedi. I am also using the latest version of typescript. Also, I am using node 11.8.0, but I get the same experience when using node 8.4.0 and older versions of  typescript.

Trying to import anything (declared) from "typedi" will result in a cannot find module typedi error.

I think that your automatically generated index.d.ts is missing the module declaration.

In order to fix this I had to add a globals.d.ts to my project

```
declare module "typedi" {
  export const Container;
  export const Service;
  // ...
}
```

Am I doing something wrong here?

Even adding node_modules/typedi/index.d.ts to my tsconfig/includes will not do the trick.

And I followed your instructions in https://github.com/typestack/typedi#usage-with-typescript

**Comment by silkentrance** [comment]
Oh well, switching from UMD to commonjs in tsconfig.json somehow did the trick, however, I need to address browsers as well.

**Comment by silkentrance** [comment]
Q: Does typedi support browsers at all?

**Comment by NoNameProvided** [comment]
This is intended, we only ship the CommonJS version. If the end project uses a different type it's up to the user to configure.
