### ISSUE TITLE
ServiceNotFoundError: Service "Request" was not found

### ISSUE THREAD

**Issue by ameetvvdn** [typestack/typedi#91]
ServiceNotFoundError: Service "Request" was not found, looks like it was not registered in the container. 
Register it by calling Container.set before using service.

I am not using Request service.As soon as i executes graphql ,the error comes.

**Comment by NoNameProvided** [comment]
Closing as not enough information is provided to help. If your issue still persists please open a new issue with minimal reproducible example.
