### ISSUE TITLE
Formalise the 'composition root' 

### ISSUE THREAD

**Issue by jasperblues** [typestack/typedi#92]
http://blog.ploeh.dk/2011/07/28/CompositionRoot/

Suggest at the very least in the README, perhaps formalising with an interface to implement, the notion of a composition root, described above. 

* The composition root should be bound to the application's entry point. In an express app, this is where we create the server. For jest tests, this is global setup method. 
* The composition root is a place to bind interfaces to concrete implementations. (Inversify does a good job at this). 
* Avoid the Service Locator anti-pattern. Ideally, the composition root should be the only place we reference a DI container. Although when tidying up a legacy app, we can introduce the DI container, using it as a service locator, gradually pulling up composition until it only occurs at the root. 

For formalising composition root, my DI container (Typhoon) had the notion of assemblies: https://github.com/appsquickly/typhoon/wiki/Types-of-Injections, though it also supported 'decorators'

**Comment by santiq** [comment]
Hello @jasperblues 

That's a great suggestion, in fact, I think I would help a lot of people that are beginners using D.I.
Would you mind to create a PR that updates the README with a good explanation of what you think is the best approach to use these good practices with typedi?

**Comment by NoNameProvided** [comment]
I will close this as wontfix. There is a lot of material out there what we could link as educational, however, the documentation should focus on explaining and promoting the best practices regarding the library. To understand the base principles behind DI the developers will read upon it if they are interested in the topic.
