### ISSUE TITLE
Is this project maintaned?

### ISSUE THREAD

**Issue by georgyfarniev** [typestack/typedi#95]
Hello. Is this project currently maintained? Last update was back in 2018, issues not getting any response, bugs not fixed. 

I'm considering forking this module, because I cannot find good alternatives.

**Comment by pleerock** [comment]
Project is quite stable, there are not so many issues, and many of them are just questions I believe. I'll consider to implement some feature requests or bugs it currently has somewhere in the future. But feel free to fork of course, it's open source and free you can do whatever you want.

**Comment by georgyfarniev** [comment]
@pleerock thanks for quick repsonse. I would like to not create fork, as long as you ready to review PR for some bugs.

**Comment by pleerock** [comment]
Personally I think its quite stable and I use it for last four or five years and still use in production environment. There might be some minor bugs or issues, I'll review all exist issues somewhere in the future when I get more free time. But as always, feel free to fork it, its open source, do whatever you want with it!

**Comment by georgyfarniev** [comment]
@pleerock thank you. I'm glad that project alive.
