### ISSUE TITLE
question: How to define a third-party dependency

### ISSUE THREAD

**Issue by jedkass** [typestack/typedi#978]
**I was trying to...**
I am trying to use TypeDI for a Node/TypeScript project. One of my classes ("services") takes an `SQS` object — a class defined by a third-party library (the AWS SDK) which I do not own — as a parameter.

**The problem:**
It seems like the only available annotations are for my own classes. So in the situation above, how am I supposed to tell the container how to instantiate an object of a class I don't own — in this case, of type `SQS`?

**Comment by attilaorosz** [comment]
Could you provide an example?

**Comment by jedkass** [comment]
Sure! Here's a dumb version of the class I have:

```
import { SQS } from 'aws-sdk'

export class SqsClient {

    private readonly sqs: SQS;

    constructor(sqs: SQS) {
        this.sqs = sqs;
    }
}
```

If I were to annotate this class with `Service()`, my understanding is that TypeDI would try to inject the `sqs: SQS` parameter. However, `sqs` needs to be created itself. Somewhere, I need to tell the container that, when I want to inject an `SQS` object, use the following definition:

```
new SQS({
    region: '<the aws region>',
    apiVersion: '2012-11-05',
});
```

It's not clear to me how I do something like this.

**Comment by attilaorosz** [comment]
You could do Container.set(SQS, new SQS(…)) on app initialization, then the DI will know what to inject.

**Comment by jedkass** [comment]
Ohhhh I see 🤦‍♂️. Thanks!
